{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\n\r\nWhen trying to plot a timeslice of a field from an open xarray DataSet with the coordinates *time*, *latitude*, and *longitude*, I get a warning indicating the presence of a datacube, and a ValueError in accessors.py expecting 2 values but getting none. I found that this problem disappears when I perform an operation on the DataArray, e.g. multiplying with `1`. The only thing that seems to change with this operation is that the attributes in xarray are dropped.\r\n\r\n**Full code that generated the error**\r\nUsing the original DataArray:\r\n```\r\nprint(ds['msl'].isel(time=i))\r\n\r\n<xarray.DataArray 'msl' (latitude: 89, longitude: 241)>\r\narray([[102200.34 , 102197.32 , 102193.22 , ..., 101123.69 , 101133.4  ,\r\n        101143.98 ],\r\n       [102182.86 , 102179.41 , 102176.59 , ..., 101061.734, 101072.31 ,\r\n        101083.1  ],\r\n       [102170.555, 102166.234, 102161.92 , ..., 100998.49 , 101009.28 ,\r\n        101020.08 ],\r\n       ...,\r\n       [101951.47 , 101926.21 , 101900.52 , ..., 101845.7  , 101869.66 ,\r\n        101891.67 ],\r\n       [102002.19 , 101976.51 , 101950.17 , ..., 101921.25 , 101941.1  ,\r\n        101961.83 ],\r\n       [102049.89 , 102023.99 , 101997.445, ..., 101993.34 , 102012.984,\r\n        102031.98 ]], dtype=float32)\r\nCoordinates:\r\n  * longitude  (longitude) float32 150.0 150.2 150.5 150.8 ... 209.5 209.8 210.0\r\n  * latitude   (latitude) float32 72.0 71.75 71.5 71.25 ... 50.5 50.25 50.0\r\n    time       datetime64[ns] 1996-11-04T06:00:00\r\nAttributes:\r\n    units:          Pa\r\n    long_name:      Mean sea level pressure\r\n    standard_name:  air_pressure_at_mean_sea_level\r\n```\r\nBreaks:\r\n```python\r\nds = xr.open_dataset(data_path) #\r\n\r\nfig = pygmt.Figure()\r\n\r\nmsl=ds['msl'].isel(time=i)\r\n\r\nfig.grdimage(grid=msl)\r\n\r\nfig.show()\r\n```\r\n\r\nUsing the DataArray multiplied by 1:\r\n```\r\nprint(ds['msl'].isel(time=i)*1)\r\n\r\n<xarray.DataArray 'msl' (latitude: 89, longitude: 241)>\r\narray([[102200.34 , 102197.32 , 102193.22 , ..., 101123.69 , 101133.4  ,\r\n        101143.98 ],\r\n       [102182.86 , 102179.41 , 102176.59 , ..., 101061.734, 101072.31 ,\r\n        101083.1  ],\r\n       [102170.555, 102166.234, 102161.92 , ..., 100998.49 , 101009.28 ,\r\n        101020.08 ],\r\n       ...,\r\n       [101951.47 , 101926.21 , 101900.52 , ..., 101845.7  , 101869.66 ,\r\n        101891.67 ],\r\n       [102002.19 , 101976.51 , 101950.17 , ..., 101921.25 , 101941.1  ,\r\n        101961.83 ],\r\n       [102049.89 , 102023.99 , 101997.445, ..., 101993.34 , 102012.984,\r\n        102031.98 ]], dtype=float32)\r\nCoordinates:\r\n  * longitude  (longitude) float32 150.0 150.2 150.5 150.8 ... 209.5 209.8 210.0\r\n  * latitude   (latitude) float32 72.0 71.75 71.5 71.25 ... 50.5 50.25 50.0\r\n    time       datetime64[ns] 1996-11-04T06:00:00\r\n```\r\nWorks:\r\n```python\r\nds = xr.open_dataset(data_path)\r\n\r\nfig = pygmt.Figure()\r\n\r\nmsl=ds['msl'].isel(time=i)*1\r\n\r\nfig.grdimage(grid=msl)\r\n\r\nfig.show()\r\n```\r\n![ERA5](https://user-images.githubusercontent.com/33000433/136988363-fe477717-6b8b-4e01-b0c6-7c5385e9284d.png)\r\n\r\n**Full error message**\r\n\r\n```\r\ngrdinfo [WARNING]: Detected a data cube (/Users/rfische1/Documents/UMD/Assistantship/POLARA/data/ERA5/ERA5_1995-2020-2.nc) but -Q not set - skipping\r\n---------------------------------------------------------------------------\r\nValueError                                Traceback (most recent call last)\r\n/var/folders/hh/2wq7ys4544ngb10v0y46_f_h0000gr/T/ipykernel_12727/718688776.py in <module>\r\n      5 msl=ds['msl'].isel(time=i)\r\n      6 \r\n----> 7 fig.grdimage(\r\n      8     grid=msl\r\n      9 )\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/site-packages/pygmt/helpers/decorators.py in new_module(*args, **kwargs)\r\n    580                     )\r\n    581                     warnings.warn(msg, category=SyntaxWarning, stacklevel=2)\r\n--> 582             return module_func(*args, **kwargs)\r\n    583 \r\n    584         new_module.aliases = aliases\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/site-packages/pygmt/helpers/decorators.py in new_module(*args, **kwargs)\r\n    723                         kwargs[arg] = separators[fmt].join(f\"{item}\" for item in value)\r\n    724             # Execute the original function and return its output\r\n--> 725             return module_func(*args, **kwargs)\r\n    726 \r\n    727         return new_module\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/site-packages/pygmt/src/grdimage.py in grdimage(self, grid, **kwargs)\r\n    171                 kwargs[\"I\"] = stack.enter_context(shading_context)\r\n    172 \r\n--> 173             fname = stack.enter_context(file_context)\r\n    174             arg_str = \" \".join([fname, build_arg_string(kwargs)])\r\n    175             lib.call_module(\"grdimage\", arg_str)\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/contextlib.py in enter_context(self, cm)\r\n    423         _cm_type = type(cm)\r\n    424         _exit = _cm_type.__exit__\r\n--> 425         result = _cm_type.__enter__(cm)\r\n    426         self._push_cm_exit(cm, _exit)\r\n    427         return result\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/contextlib.py in __enter__(self)\r\n    111         del self.args, self.kwds, self.func\r\n    112         try:\r\n--> 113             return next(self.gen)\r\n    114         except StopIteration:\r\n    115             raise RuntimeError(\"generator didn't yield\") from None\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/site-packages/pygmt/clib/session.py in virtualfile_from_grid(self, grid)\r\n   1335         >>> # The output is: w e s n z0 z1 dx dy n_columns n_rows reg gtype\r\n   1336         \"\"\"\r\n-> 1337         _gtype = {0: \"GMT_GRID_IS_CARTESIAN\", 1: \"GMT_GRID_IS_GEO\"}[grid.gmt.gtype]\r\n   1338         _reg = {0: \"GMT_GRID_NODE_REG\", 1: \"GMT_GRID_PIXEL_REG\"}[grid.gmt.registration]\r\n   1339 \r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/site-packages/xarray/core/extensions.py in __get__(self, obj, cls)\r\n     34 \r\n     35         try:\r\n---> 36             accessor_obj = self._accessor(obj)\r\n     37         except AttributeError:\r\n     38             # __getattr__ on data object will swallow any AttributeErrors\r\n\r\n~/opt/anaconda3/envs/name/lib/python3.8/site-packages/pygmt/accessors.py in __init__(self, xarray_obj)\r\n     32             # From the shortened summary information of `grdinfo`,\r\n     33             # get grid registration in column 10, and grid type in column 11\r\n---> 34             self._registration, self._gtype = map(\r\n     35                 int, grdinfo(self._source, per_column=\"n\", o=\"10,11\").split()\r\n     36             )\r\n\r\nValueError: not enough values to unpack (expected 2, got 0)\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.4.1\r\nSystem information:\r\n  python: 3.8.11 (default, Aug  6 2021, 08:56:27)  [Clang 10.0.0 ]\r\n  executable: /Users/name/opt/anaconda3/envs/name/bin/python\r\n  machine: macOS-10.16-x86_64-i386-64bit\r\nDependency information:\r\n  numpy: 1.21.2\r\n  pandas: 1.3.3\r\n  xarray: 0.19.0\r\n  netCDF4: 1.5.7\r\n  packaging: 21.0\r\n  ghostscript: 9.54.0\r\n  gmt: 6.2.0\r\nGMT library information:\r\n  binary dir: /Users/name/opt/anaconda3/envs/name/bin\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: /Users/name/opt/anaconda3/envs/name/lib/libgmt.dylib\r\n  padding: 2\r\n  plugin dir: /Users/name/opt/anaconda3/envs/name/lib/gmt/plugins\r\n  share dir: /Users/name/opt/anaconda3/envs/name/share/gmt\r\n  version: 6.2.0\r\n```\r\n",
    "closed_at": "2021-10-28T21:54:50Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    },
    "comments": 4,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "Hi @reint-fischer, thanks for trying out PyGMT!\r\n\r\nSo the `Detected a data cube` error indicates that you may be passing in a array with 3 dimensions (e.g. time, latitude and longitude). The solution would be to use `.isel` to select a single time slice (as you have discovered), so that there are only latitude and longitude coordinates, and `ds.shape` should return a tuple with two numbers (e.g. `(180, 360)`).\r\n\r\nAs to why it's not working, could you please provide the output of `print(ds)` for the two `xarray.DataArray` objects you used, the one that worked and the one that didn't? It's a bit hard to tell from your code what's going on (also, I think you posted the same code twice, could you edit your original post to clarify things?). Once you've done that, we should be able to see what's going on, and how you can modify your data to get it plotted.",
            "created_at": "2021-10-12T03:13:38Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1578#issuecomment-940617768",
            "id": 940617768,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578",
            "node_id": "IC_kwDOBRZfO844ELAo",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/940617768/reactions"
            },
            "updated_at": "2021-10-12T03:14:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/940617768",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "NONE",
            "body": "hi @weiji14 ,\r\n\r\nsorry for the confusion, I updated my original post. The crucial part that I forgot is the multiplying by 1: `ds['msl'].isel(time=i)*1`. I have printed the two DataArrays and as you can see, the only difference seems to be the attributes.\r\n\r\nRelating to the datacube message I have tried alternative ways of selecting the data, but I always have a 2D slice as input and it only works when the attributes are not there.\r\n\r\nI should also note again that the multiplication by 1 is a good workaround for me, so the bug is not very urgent, it just took me a while to figure it out and I think it would be nice to prevent people from running into this in the future.\r\n\r\nThanks for replying so quickly",
            "created_at": "2021-10-12T15:50:42Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1578#issuecomment-941140743",
            "id": 941140743,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578",
            "node_id": "IC_kwDOBRZfO844GKsH",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/941140743/reactions"
            },
            "updated_at": "2021-10-12T16:01:53Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/941140743",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/33000433?v=4",
                "events_url": "https://api.github.com/users/reint-fischer/events{/privacy}",
                "followers_url": "https://api.github.com/users/reint-fischer/followers",
                "following_url": "https://api.github.com/users/reint-fischer/following{/other_user}",
                "gists_url": "https://api.github.com/users/reint-fischer/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/reint-fischer",
                "id": 33000433,
                "login": "reint-fischer",
                "node_id": "MDQ6VXNlcjMzMDAwNDMz",
                "organizations_url": "https://api.github.com/users/reint-fischer/orgs",
                "received_events_url": "https://api.github.com/users/reint-fischer/received_events",
                "repos_url": "https://api.github.com/users/reint-fischer/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/reint-fischer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/reint-fischer/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/reint-fischer"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Ah I see what's going on now. So this is the same issue as mentioned in https://github.com/GenericMappingTools/pygmt/issues/524#issuecomment-904185638. Long story short, the error happens because `grdimage` runs `grdinfo` to extract some metadata before plotting, and `grdinfo` is attempting to read off of your original ERA5 NetCDF file (accessed using `ds.encoding[\"source\"]`) but cannot since it is a datacube.\r\n\r\nYour multiplying by 1 workaround (which is very smart by the way!) works because it resets `ds.encoding[\"source\"]` to nothing (i.e. it won't be able to find your ERA5 NetCDF file). What we might do is to modify this try-except block:\r\n\r\nhttps://github.com/GenericMappingTools/pygmt/blob/5cb1035dd4e8fdaeec1d0421b4cbc58392dff29b/pygmt/accessors.py#L30-L39\r\n\r\nWe'll need to update it to fallback nicely when `grdinfo` doesn't work (e.g. for datacubes). I'll try to work on a bugfix for this, but in the meantime, you can continue using your workaround, or do something like this:\r\n\r\n```python\r\nmsl = ds['msl'].isel(time=i)\r\nmsl.encoding.pop(\"source\")  # removes link to NetCDF file\r\nfig.grdimage(grid=msl)\r\n```\r\n\r\nTo help us out a little, do you have a link to a publicly available dataset like the ERA5 NetCDF file you used? Would make it easier for us to test things out. Edit: I've opened a bugfix at #1581, hopefully we'll get this fixed by the next PyGMT v0.5.0 release coming end of Oct.",
            "created_at": "2021-10-12T23:18:46Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1578#issuecomment-941735916",
            "id": 941735916,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578",
            "node_id": "IC_kwDOBRZfO844Ib_s",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/941735916/reactions"
            },
            "updated_at": "2021-10-13T02:57:46Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/941735916",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@reint-fischer, the bugfix has been merged at #1581 so `fig.grdimage(grid=msl)` should work on your sliced data cube. We're just about to release PyGMT v0.5.0 tomorrow, so if you update PyGMT next week, things should work :grin:",
            "created_at": "2021-10-28T21:59:48Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1578#issuecomment-954254165",
            "id": 954254165,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578",
            "node_id": "IC_kwDOBRZfO8444MNV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/954254165/reactions"
            },
            "updated_at": "2021-10-28T21:59:48Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/954254165",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578/comments",
    "created_at": "2021-10-12T01:39:53Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1578",
    "id": 1023267190,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2021-10-31T23:31:11Z",
        "closed_issues": 137,
        "created_at": "2021-03-16T21:12:52Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
            "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
            "followers_url": "https://api.github.com/users/weiji14/followers",
            "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
            "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/weiji14",
            "id": 23487320,
            "login": "weiji14",
            "node_id": "MDQ6VXNlcjIzNDg3MzIw",
            "organizations_url": "https://api.github.com/users/weiji14/orgs",
            "received_events_url": "https://api.github.com/users/weiji14/received_events",
            "repos_url": "https://api.github.com/users/weiji14/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/weiji14"
        },
        "description": "https://github.com/GenericMappingTools/pygmt/issues/1576",
        "due_on": "2021-10-29T07:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/8",
        "id": 6553956,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/8/labels",
        "node_id": "MDk6TWlsZXN0b25lNjU1Mzk1Ng==",
        "number": 8,
        "open_issues": 0,
        "state": "closed",
        "title": "0.5.0",
        "updated_at": "2022-09-22T11:49:00Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/8"
    },
    "node_id": "I_kwDOBRZfO848_dF2",
    "number": 1578,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578/timeline",
    "title": "xarray DataArray attributes breaking grdimage",
    "updated_at": "2021-10-28T21:59:48Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1578",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/33000433?v=4",
        "events_url": "https://api.github.com/users/reint-fischer/events{/privacy}",
        "followers_url": "https://api.github.com/users/reint-fischer/followers",
        "following_url": "https://api.github.com/users/reint-fischer/following{/other_user}",
        "gists_url": "https://api.github.com/users/reint-fischer/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/reint-fischer",
        "id": 33000433,
        "login": "reint-fischer",
        "node_id": "MDQ6VXNlcjMzMDAwNDMz",
        "organizations_url": "https://api.github.com/users/reint-fischer/orgs",
        "received_events_url": "https://api.github.com/users/reint-fischer/received_events",
        "repos_url": "https://api.github.com/users/reint-fischer/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/reint-fischer/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/reint-fischer/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/reint-fischer"
    }
}