{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\nAs I am working on #966, I first ran the examples on [pygmt.datasets.load_earth_relief](https://www.pygmt.org/latest/api/generated/pygmt.datasets.load_earth_relief.html#pygmt.datasets.load_earth_relief). However, it seems that `load_earth_relief()` may have a bug to find low-resolution earth relief files, which seems to be related to `which`.\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\n>>> from pygmt.datasets import load_earth_relief\r\n>>> grid = load_earth_relief()\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/core-man/src/pygmt/pygmt/helpers/decorators.py\", line 425, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/home/core-man/src/pygmt/pygmt/datasets/earth_relief.py\", line 111, in load_earth_relief\r\n    fname = which(f\"@earth_relief_{resolution}{reg}\", download=\"a\")\r\n  File \"/home/core-man/src/pygmt/pygmt/helpers/decorators.py\", line 281, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/home/core-man/src/pygmt/pygmt/src/which.py\", line 55, in which\r\n    raise FileNotFoundError(\"File '{}' not found.\".format(fname))\r\nFileNotFoundError: File '@earth_relief_01d' not found.\r\n```\r\n\r\nI also tested high-resolution earth relief. `load_earth_relief()` uses `grdcut` to handle it instead of `which`.\r\n\r\n```python\r\n>>> from pygmt.datasets import load_earth_relief\r\n>>> grid = load_earth_relief(\"05m\", region=[120, 160, 30, 60], registration=\"gridline\")\r\ngrdblend [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\ngrdblend [NOTICE]: Earth Relief at 5x5 arc minutes from Gaussian Cartesian filtering (9 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngrdblend [NOTICE]:   -> Download 180x180 degree grid tile (earth_relief_05m_g): S90E000\r\n```\r\n\r\nBoth high- and low-resolution earth relief files have been downloaded.\r\n\r\n```bash\r\n# Check GMT Earth data directory\r\n$ ls ~/.gmt/server/earth/earth_relief\r\nearth_relief_01d_p.grd  earth_relief_05m_g\r\n$ ls ~/.gmt/server/earth/earth_relief/earth_relief_05m_g \r\nS90E000.earth_relief_05m_g.nc\r\n```\r\n\r\nThen I used `gmt which` command in the terminal to check those files:\r\n\r\n```bash\r\n# High resolution @earth_relief_05m_g\r\n$ gmt which @earth_relief_05m_g                 \r\ngmtwhich [ERROR]: Tile @S90W180.earth_relief_05m_g.nc not found!\r\n/home/core-man/.gmt/server/earth/earth_relief/earth_relief_05m_g/S90E000.earth_relief_05m_g.nc\r\n$ gmt which @S90E000.earth_relief_05m_g.nc\r\n/home/core-man/.gmt/server/earth/earth_relief/earth_relief_05m_g/S90E000.earth_relief_05m_g.nc\r\n\r\n# Low resolution @earth_relief_01d\r\n$ gmt which @earth_relief_01d_p.grd                            \r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n$ gmt which @earth_relief_01d_p    \r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n$ gmt which @earth_relief_01d  \r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.3.1.dev34+g4db28ef\r\nSystem information:\r\n  python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46)  [GCC 9.3.0]\r\n  executable: /home/core-man/.anaconda3/envs/pygmt/bin/python\r\n  machine: Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-glibc2.17\r\nDependency information:\r\n  numpy: 1.20.1\r\n  pandas: 1.2.2\r\n  xarray: 0.16.2\r\n  netCDF4: 1.5.6\r\n  packaging: 20.9\r\n  ghostscript: 9.53.3\r\n  gmt: 6.1.1\r\nGMT library information:\r\n  binary dir: /home/core-man/.anaconda3/envs/pygmt/bin\r\n  cores: 8\r\n  grid layout: rows\r\n  library path: /home/core-man/.anaconda3/envs/pygmt/lib/libgmt.so\r\n  padding: 2\r\n  plugin dir: /home/core-man/.anaconda3/envs/pygmt/lib/gmt/plugins\r\n  share dir: /home/core-man/.anaconda3/envs/pygmt/share/gmt\r\n  version: 6.1.1\r\n```\r\n",
    "closed_at": "2021-03-02T14:57:37Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 15,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/master/CODE_OF_CONDUCT.md).\n",
            "created_at": "2021-02-26T13:33:55Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-786650685",
            "id": 786650685,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NjY1MDY4NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786650685/reactions"
            },
            "updated_at": "2021-02-26T13:33:55Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786650685",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Could you please post the output of\r\n```\r\ngmt --version\r\ngmt which @earth_relief_01d_p.grd -Vd\r\n```",
            "created_at": "2021-02-26T14:29:43Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-786680841",
            "id": 786680841,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NjY4MDg0MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786680841/reactions"
            },
            "updated_at": "2021-02-26T14:29:43Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786680841",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@seisman \r\n\r\n```\r\n$ gmt --version\r\n6.1.1\r\n```\r\n\r\n```\r\n$ gmt which @earth_relief_01d_p.grd -Vd\r\ngmt [DEBUG]: Obtained the ppid from parent: 105618\r\ngmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl\r\ngmt [DEBUG]: GMT->session.SHAREDIR = /home/core-man/.anaconda3/envs/pygmt/share/gmt\r\ngmt [DEBUG]: GMT->session.HOMEDIR = /home/core-man\r\ngmt [DEBUG]: GMT->session.USERDIR = /home/core-man/.gmt [created]\r\ngmt [DEBUG]: GMT->session.CACHEDIR = /home/core-man/.gmt/cache [created]\r\ngmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt\r\ngmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir\r\ngmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /home/core-man/.gmt\r\ngmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /home/core-man/.gmt/postscriptlight\r\ngmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /home/core-man/.anaconda3/envs/pygmt/share/gmt/postscriptlight\r\ngmt [DEBUG]: GMT: 5. gmt_getsharepath trying SHAREDIR /home/core-man/.anaconda3/envs/pygmt/share/gmt\r\ngmt [DEBUG]: GMT: 6. gmt_getsharepath failed\r\ngmt [DEBUG]: Map distance calculation will be Cartesian\r\ngmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl\r\ngmt [DEBUG]: Enter: New_PSL_Ctrl\r\ngmt [DEBUG]: Exit:  New_PSL_Ctrl\r\ngmt [DEBUG]: Enter: gmt_manage_workflow\r\ngmt [DEBUG]: Exit : gmt_manage_workflow\r\ngmt [DEBUG]: Enter: PSL_beginsession\r\ngmt [DEBUG]: Exit : PSL_beginsession\r\ngmt [DEBUG]: Enter: PSL_setdefaults\r\ngmt [DEBUG]: Exit : PSL_setdefaults\r\ngmt [DEBUG]: Enter: gmtlib_io_init\r\ngmt [DEBUG]: Exit : gmtlib_io_init\r\ngmt [DEBUG]: Enter: gmt_hash_init\r\ngmt [DEBUG]: Exit:  gmt_hash_init\r\ngmt [DEBUG]: Enter: gmt_hash_init\r\ngmt [DEBUG]: Exit:  gmt_hash_init\r\ngmt [DEBUG]: Enter: gmt_reload_settings\r\ngmt [DEBUG]: The PROJ_GEODESIC set to Vincenty\r\ngmt [DEBUG]: Look for file /home/core-man/gmt.conf\r\ngmt [DEBUG]: Look for file /home/core-man/.gmt/gmt.conf\r\ngmt [DEBUG]: Look for file /home/core-man/.gmt/server/gmt.conf\r\ngmt [DEBUG]: Look for file /home/core-man/.gmt/cache/gmt.conf\r\ngmt [DEBUG]: Could not find file gmt.conf\r\ngmt [DEBUG]: Exit:  gmt_reload_settings\r\ngmt [DEBUG]: Enter: gmtlib_plot_C_format\r\ngmt [DEBUG]: Exit:  gmtlib_plot_C_format\r\ngmt [DEBUG]: Enter: gmtinit_get_history\r\ngmt [DEBUG]: Initialize FFTW with 8 threads.\r\ngmt [DEBUG]: GMT_Create_Session initialized GMT structure\r\ngmt [DEBUG]: Loading core GMT shared library: libgmt.so\r\ngmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.so\r\ngmt [DEBUG]: Loading GMT plugins from: /home/core-man/.anaconda3/envs/pygmt/lib/gmt/plugins\r\ngmt [DEBUG]: Shared Library # 1 (supplements). Path = /home/core-man/.anaconda3/envs/pygmt/lib/gmt/plugins/supplements.so\r\ngmt [DEBUG]: Local file /home/core-man/.gmt/server/gmt_data_server.txt found\r\ngmt [DEBUG]: File /home/core-man/.gmt/server/gmt_data_server.txt less than 24 hours old, refresh is premature.\r\ngmt [DEBUG]: Load contents from /home/core-man/.gmt/server/gmt_data_server.txt\r\ngmt [DEBUG]: Local file /home/core-man/.gmt/server/gmt_hash_server.txt found\r\ngmt [DEBUG]: File /home/core-man/.gmt/server/gmt_hash_server.txt less than 24 hours old, refresh is premature.\r\ngmt [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.\r\ngmt [DEBUG]: Revised options: @earth_relief_01d_p -Vd\r\ngmtwhich [DEBUG]: gmtapi_init_export: Passed family = Data Table and geometry = Text\r\ngmtwhich [DEBUG]: Object ID 0 : Registered Data Table Stream 7fae37791400 as an Output resource with geometry Text [n_objects = 1]\r\ngmtwhich [DEBUG]: gmtapi_init_export: Added stdout to registered destinations\r\ngmtwhich [DEBUG]: GMT_Init_IO: Returned first Output object ID = 0\r\ngmtwhich [DEBUG]: GMT_Begin_IO: Initialize record-by-record access for Output\r\ngmtwhich [DEBUG]: gmtapi_next_io_source: Selected object 0\r\ngmtwhich [INFORMATION]: Writing Data Table to Standard Output stream\r\ngmtwhich [DEBUG]: GMT_Begin_IO: Output resource access is now enabled [record-by-record]\r\ngmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /home/core-man/.gmt\r\ngmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /home/core-man/.gmt/cache\r\ngmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /home/core-man/.gmt/server\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\ngmtwhich [DEBUG]: GMT_End_IO: Output resource access is now disabled\r\ngmtwhich [DEBUG]: gmtlib_unregister_io: Unregistering object no 0 [n_objects = 0]\r\ngmtwhich (gmtlib_free_tmp_arrays): tried to free unallocated memory\r\ngmt [DEBUG]: Entering GMT_Destroy_Session\r\n```\r\n\r\n",
            "created_at": "2021-02-26T14:41:15Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-786687854",
            "id": 786687854,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NjY4Nzg1NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786687854/reactions"
            },
            "updated_at": "2021-02-26T14:41:15Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786687854",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/50591376?v=4",
                "events_url": "https://api.github.com/users/core-man/events{/privacy}",
                "followers_url": "https://api.github.com/users/core-man/followers",
                "following_url": "https://api.github.com/users/core-man/following{/other_user}",
                "gists_url": "https://api.github.com/users/core-man/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/core-man",
                "id": 50591376,
                "login": "core-man",
                "node_id": "MDQ6VXNlcjUwNTkxMzc2",
                "organizations_url": "https://api.github.com/users/core-man/orgs",
                "received_events_url": "https://api.github.com/users/core-man/received_events",
                "repos_url": "https://api.github.com/users/core-man/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/core-man/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/core-man/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/core-man"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "It's weird. I don't see anything wrong in the output.",
            "created_at": "2021-02-26T14:58:22Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-786698110",
            "id": 786698110,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NjY5ODExMA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786698110/reactions"
            },
            "updated_at": "2021-02-26T14:58:22Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786698110",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@PaulWessel Do you have any idea why `gmt which` can't find the remote file even though it's already downloaded?",
            "created_at": "2021-02-26T20:34:10Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-786879728",
            "id": 786879728,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4Njg3OTcyOA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786879728/reactions"
            },
            "updated_at": "2021-02-26T20:34:10Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/786879728",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "On the face of it, no.  But if I delete my copy and run that command I get the same error.  I think you need **-G** if you want to download a file via gmt which though.\r\n\r\n\r\n",
            "created_at": "2021-02-27T21:35:03Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-787151124",
            "id": 787151124,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NzE1MTEyNA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787151124/reactions"
            },
            "updated_at": "2021-02-27T21:35:03Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787151124",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@core-man Is it possible that the earth_relief_01d_p.grd file is not complete due to unstable internet connections? Could you check the file size and md5sum?",
            "created_at": "2021-02-27T21:52:25Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-787170675",
            "id": 787170675,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4NzE3MDY3NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787170675/reactions"
            },
            "updated_at": "2021-02-27T21:52:25Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787170675",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> @core-man Is it possible that the earth_relief_01d_p.grd file is not complete due to unstable internet connections? Could you check the file size and md5sum?\r\n\r\n@seisman \r\n\r\nDownload earth relief grid via `load_earth_relief()`:\r\n\r\n```bash\r\n$ python\r\n>>> from pygmt.datasets import load_earth_relief\r\n>>> grid = load_earth_relief()\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/core-man/src/pygmt/pygmt/helpers/decorators.py\", line 425, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/home/core-man/src/pygmt/pygmt/datasets/earth_relief.py\", line 111, in load_earth_relief\r\n    fname = which(f\"@earth_relief_{resolution}{reg}\", download=\"a\")\r\n  File \"/home/core-man/src/pygmt/pygmt/helpers/decorators.py\", line 281, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"/home/core-man/src/pygmt/pygmt/src/which.py\", line 55, in which\r\n    raise FileNotFoundError(\"File '{}' not found.\".format(fname))\r\nFileNotFoundError: File '@earth_relief_01d' not found.\r\n```\r\n\r\nRename the grid to be `earth_relief_01d_p_load.grd`:\r\n\r\n```bash\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p.grd\r\n$ mv ~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd ~/.gmt/server/earth/earth_relief/earth_relief_01d_p_load.grd\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p_load.grd\r\n```\r\n\r\nThen I can use the `grdimage` to download and plot `@earth_relief_01d`.\r\n\r\n```Python\r\nimport pygmt\r\n\r\nfig = pygmt.Figure()\r\nfig.grdimage(grid=\"@earth_relief_01d\")\r\nfig.show()\r\n```\r\n\r\n```bash\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p.grd  earth_relief_01d_p_load.grd\r\n```\r\n\r\nThe two grids are the same.\r\n\r\n```bash\r\n$ du -h ~/.gmt/server/earth/earth_relief/*\r\n116K\t/home/core-man/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\r\n116K\t/home/core-man/.gmt/server/earth/earth_relief/earth_relief_01d_p_load.grd\r\n\r\n$ diff ~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd ~/.gmt/server/earth/earth_relief/earth_relief_01d_p_load.grd\r\n\r\n$ md5sum ~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd ~/.gmt/server/earth/earth_relief/earth_relief_01d_p_load.grd\r\n74a884c902015dda516d17605f317efe  /home/core-man/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\r\n74a884c902015dda516d17605f317efe  /home/core-man/.gmt/server/earth/earth_relief/earth_relief_01d_p_load.grd\r\n```\r\n",
            "created_at": "2021-03-01T08:52:14Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-787774891",
            "id": 787774891,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4Nzc3NDg5MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787774891/reactions"
            },
            "updated_at": "2021-03-01T10:15:44Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787774891",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/50591376?v=4",
                "events_url": "https://api.github.com/users/core-man/events{/privacy}",
                "followers_url": "https://api.github.com/users/core-man/followers",
                "following_url": "https://api.github.com/users/core-man/following{/other_user}",
                "gists_url": "https://api.github.com/users/core-man/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/core-man",
                "id": 50591376,
                "login": "core-man",
                "node_id": "MDQ6VXNlcjUwNTkxMzc2",
                "organizations_url": "https://api.github.com/users/core-man/orgs",
                "received_events_url": "https://api.github.com/users/core-man/received_events",
                "repos_url": "https://api.github.com/users/core-man/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/core-man/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/core-man/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/core-man"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> On the face of it, no. But if I delete my copy and run that command I get the same error. I think you need **-G** if you want to download a file via gmt which though.\r\n\r\n@seisman @PaulWessel \r\nYes, I can use `-G` to download and find the grid.\r\n\r\n```\r\n# work in ~/workspace folder\r\n$ cd ~/workspace\r\n\r\n# use `-Gl` option\r\n$ ls\r\n$ gmt which -Gl @earth_relief_01d_p\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\n\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\nearth_relief_01d_p.grd\r\n$ ls\r\nearth_relief_01d_p.grd\r\n\r\n# Use `-Ga` option\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\n$ gmt which -Ga @earth_relief_01d_p\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\n\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\nearth_relief_01d_p.grd\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p.grd\r\n\r\n# those two grids are the same\r\n$ diff ./earth_relief_01d_p.grd ~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\r\n```\r\n\r\nHowever, there could still exist some bugs. A strange thing occurred. If the grid is the current folder is deleted and the grid in `~/.gmt/server/earth/earth_relief/` is kept, neither `gmt which -Gl` nor `gmt which -Ga` can work.\r\n```bash\r\n# I am still in ~/workspace\r\n$ ls\r\nearth_relief_01d_p.grd\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p.grd\r\n\r\n# remove the grid in the current folder\r\n$ rm ./earth_relief_01d_p.grd\r\n\r\n# gmt which cannot work\r\n$ gmt which -Gl @earth_relief_01d_p\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n$ gmt which -Ga @earth_relief_01d_p\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n```\r\n\r\nI removed `~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd`. I then ran commands in the above first window again and they work.\r\n```\r\n# I am still in ~/workspace which is empty now\r\n$ ls\r\n$ rm ~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\n\r\n# use `-Gl` option\r\n$ ls\r\n$ gmt which -Gl @earth_relief_01d_p\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\n\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\nearth_relief_01d_p.grd\r\n$ ls\r\nearth_relief_01d_p.grd\r\n\r\n# Use `-Ga` option\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\n$ gmt which -Ga @earth_relief_01d_p\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\n\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\nearth_relief_01d_p.grd\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p.grd\r\n```\r\n\r\nFinally, I removed the grids in the current folder and `~/.gmt/server/earth/earth_relief/`. `gmt which -Ga` can download the grid but cannot find the grid.\r\n```bash\r\n# I am still in ~/workspace\r\n$ rm earth_relief_01d_p.grd ~/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd\r\n\r\n$ gmt which @earth_relief_01d_p\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n$ ls\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\n\r\n$ gmt which -Ga @earth_relief_01d_p\r\ngmtwhich [NOTICE]: Remote data courtesy of GMT data server OCEANIA [https://oceania.generic-mapping-tools.org]\r\n\r\ngmtwhich [NOTICE]: Earth Relief at 1x1 arc degrees from Gaussian Cartesian filtering (111 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019].\r\ngmtwhich [NOTICE]:   -> Download grid file [115K]: earth_relief_01d_p.grd\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n\r\n$ ls\r\n$ ls ~/.gmt/server/earth/earth_relief/\r\nearth_relief_01d_p.grd\r\n\r\n$ gmt which @earth_relief_01d_p \r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n\r\n$ gmt which -Gl @earth_relief_01d_p\r\ngmtwhich [ERROR]: File earth_relief_01d_p.grd not found!\r\n$ ls\r\n```\r\n\r\nIn summary:\r\n1. If there is the same grid in `~/.gmt/server/earth/earth_relief/`, `gmt which -Gl` cannot work.\r\n2. If there is no the same grid in the current folder, `gmt which -Ga` can download the grid to `~/.gmt/server/earth/earth_relief` but cannot find it.\r\n3. If there is the same grid in the current folder, `gmt which -Ga` can download the grid to `~/.gmt/server/earth/earth_relief` and can find a grid with the same name.\r\n4. It seems that the file `gmt which -Ga` tries to find is the grid in the current folder instead of `~/.gmt/server/earth/earth_relief`.\r\n\r\n\r\n",
            "created_at": "2021-03-01T08:56:39Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-787777937",
            "id": 787777937,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4Nzc3NzkzNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787777937/reactions"
            },
            "updated_at": "2021-03-01T10:02:27Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/787777937",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/50591376?v=4",
                "events_url": "https://api.github.com/users/core-man/events{/privacy}",
                "followers_url": "https://api.github.com/users/core-man/followers",
                "following_url": "https://api.github.com/users/core-man/following{/other_user}",
                "gists_url": "https://api.github.com/users/core-man/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/core-man",
                "id": 50591376,
                "login": "core-man",
                "node_id": "MDQ6VXNlcjUwNTkxMzc2",
                "organizations_url": "https://api.github.com/users/core-man/orgs",
                "received_events_url": "https://api.github.com/users/core-man/received_events",
                "repos_url": "https://api.github.com/users/core-man/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/core-man/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/core-man/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/core-man"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Thanks for the detailed reports. However, I followed your steps but still can't reproduce your issue. I'm using GMT 6.1.1 (installed using conda) on macOS.",
            "created_at": "2021-03-02T04:46:36Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-788581132",
            "id": 788581132,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4ODU4MTEzMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788581132/reactions"
            },
            "updated_at": "2021-03-02T04:46:36Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788581132",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Thanks for the detailed reports. However, I followed your steps but still can't reproduce your issue. I'm using GMT 6.1.1 (installed using conda) on macOS.\r\n\r\nI use GMT 6.1.1 (installed using conda) CentOS7. I don't have this issue on my macOS either.",
            "created_at": "2021-03-02T05:21:41Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-788600607",
            "id": 788600607,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4ODYwMDYwNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788600607/reactions"
            },
            "updated_at": "2021-03-02T05:21:41Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788600607",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/50591376?v=4",
                "events_url": "https://api.github.com/users/core-man/events{/privacy}",
                "followers_url": "https://api.github.com/users/core-man/followers",
                "following_url": "https://api.github.com/users/core-man/following{/other_user}",
                "gists_url": "https://api.github.com/users/core-man/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/core-man",
                "id": 50591376,
                "login": "core-man",
                "node_id": "MDQ6VXNlcjUwNTkxMzc2",
                "organizations_url": "https://api.github.com/users/core-man/orgs",
                "received_events_url": "https://api.github.com/users/core-man/received_events",
                "repos_url": "https://api.github.com/users/core-man/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/core-man/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/core-man/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/core-man"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I just tried GMT 6.1.1 on CentOS 7.8. Still can't reproduce your issue.",
            "created_at": "2021-03-02T05:48:05Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-788631690",
            "id": 788631690,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4ODYzMTY5MA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788631690/reactions"
            },
            "updated_at": "2021-03-02T05:48:05Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788631690",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I just tried GMT 6.1.1 on CentOS 7.8. Still can't reproduce your issue.\r\n\r\nI use CentOS 7.5. I also use the GMT built from the source code (6.2.0_416e03f_2020.08.18) instead of conda and it also has the same bug.\r\n\r\nIf only I have the bug, it should be okay cause I also work on macOS. Maybe it is caused by an unknown/strange thing in my CentOS. Shall we close this issue or open it until someone also have this issue?",
            "created_at": "2021-03-02T12:07:09Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-788861946",
            "id": 788861946,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4ODg2MTk0Ng==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788861946/reactions"
            },
            "updated_at": "2021-03-02T12:09:31Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788861946",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/50591376?v=4",
                "events_url": "https://api.github.com/users/core-man/events{/privacy}",
                "followers_url": "https://api.github.com/users/core-man/followers",
                "following_url": "https://api.github.com/users/core-man/following{/other_user}",
                "gists_url": "https://api.github.com/users/core-man/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/core-man",
                "id": 50591376,
                "login": "core-man",
                "node_id": "MDQ6VXNlcjUwNTkxMzc2",
                "organizations_url": "https://api.github.com/users/core-man/orgs",
                "received_events_url": "https://api.github.com/users/core-man/received_events",
                "repos_url": "https://api.github.com/users/core-man/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/core-man/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/core-man/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/core-man"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I will close this one. Feel free to reopen it if someone else can reproduce the issue or have a clue why it doesn't work.",
            "created_at": "2021-03-02T14:57:34Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-788968143",
            "id": 788968143,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4ODk2ODE0Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788968143/reactions"
            },
            "updated_at": "2021-03-02T14:57:34Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788968143",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I don't have a way to reproduce the issue, but I wanted to point out that this seems similar in some ways to an issue that I had earlier which could not be reproduced by other users: https://github.com/GenericMappingTools/gmt/issues/4522. So, it could be related to the specific user environment rather than the OS.",
            "created_at": "2021-03-02T15:05:59Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972#issuecomment-788974517",
            "id": 788974517,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc4ODk3NDUxNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788974517/reactions"
            },
            "updated_at": "2021-03-02T15:05:59Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/788974517",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972/comments",
    "created_at": "2021-02-26T13:33:54Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/972",
    "id": 817360774,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU4MTczNjA3NzQ=",
    "number": 972,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972/timeline",
    "title": "load_earth_relief() failed to find earth relief files",
    "updated_at": "2021-03-02T15:05:59Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/972",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/50591376?v=4",
        "events_url": "https://api.github.com/users/core-man/events{/privacy}",
        "followers_url": "https://api.github.com/users/core-man/followers",
        "following_url": "https://api.github.com/users/core-man/following{/other_user}",
        "gists_url": "https://api.github.com/users/core-man/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/core-man",
        "id": 50591376,
        "login": "core-man",
        "node_id": "MDQ6VXNlcjUwNTkxMzc2",
        "organizations_url": "https://api.github.com/users/core-man/orgs",
        "received_events_url": "https://api.github.com/users/core-man/received_events",
        "repos_url": "https://api.github.com/users/core-man/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/core-man/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/core-man/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/core-man"
    }
}