{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "\r\n<img width=\"911\" alt=\"screen shot 2018-04-20 at 16 54 44\" src=\"https://user-images.githubusercontent.com/37407269/39061246-94aed9da-44bb-11e8-945b-cff9c77a53d9.png\">\r\nHi, I've been trying to install gmt-python for the past day and a half with no avail. I am on macOS 10.13.4, Python 3.6.5 (installed with Anaconda 3). I've been following all of the installation instruction, and everything seems fine except when I get to the very end, with the gmt.test().\r\n\r\nI am in the conda environment (using source activate gmt-python), and trying this in the Python interpreter. This is what happens: \r\n\r\n>>> **(gmt-python) Chandras-MacBook-Pro:~ chandra$** python\r\nPython 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09)\r\n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> >>> import gmt\r\n>>> gmt.test()\r\n\r\nreturns\r\n\r\n>>> ============================= test session starts ==============================\r\nplatform darwin -- Python 3.6.5, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /anaconda3/envs/gmt-python/bin/python\r\ncachedir: .pytest_cache\r\nMatplotlib: 2.2.2\r\nFreetype: 2.8.1\r\nrootdir: /Users/chandra, inifile:\r\nplugins: mpl-0.9\r\ncollected 126 items\r\ngmt/base_plotting.py::gmt.base_plotting.BasePlotting._preprocess <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/base_plotting.py **PASSED [  0%]**\r\ngmt/figure.py::gmt.figure.Figure <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/figure.py **FAILED [  1%]**\r\ngmt/clib/core.py::gmt.clib.core.LibGMT <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py **PASSED [  2%]**\r\ngmt/clib/core.py::gmt.clib.core.LibGMT._check_dtype_and_dim <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py **PASSED [  3%]**\r\ngmt/clib/core.py::gmt.clib.core.LibGMT.extract_region <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py gmt-python-session [ERROR]: Long input record (236 bytes) was truncated to first 126 bytes!\r\n**FAILED [  3%]**\r\ngmt/clib/core.py::gmt.clib.core.LibGMT.grid_to_vfile <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py **FAILED [  4%]**\r\ngmt/clib/core.py::gmt.clib.core.LibGMT.log_to_file <- ../../anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py **Segmentation fault: 11**\r\n\r\nI feel like this might be because of a bash profile issue. I am not sure how to set up a .bashrc profile properly on the Mac (sorry!), but my .bash_profile looks like this (note the 'added by...' *is* commented out):\r\n\r\n>>> *added by Anaconda3 5.1.0 installer*\r\nexport PATH=\"/anaconda3/bin:$PATH\"\r\n>>> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/anaconda3/envs/gmt-python/lib\r\n\r\nAny help would be much appreciated! \ud83d\ude04 \r\nps. let me know if any clarifications are needed, sorry first time writing an issue in!\r\npps. attached a screenshot of terminal, just to be super clear!",
    "closed_at": "2018-06-16T04:34:39Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
        "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
        "followers_url": "https://api.github.com/users/leouieda/followers",
        "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
        "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/leouieda",
        "id": 290082,
        "login": "leouieda",
        "node_id": "MDQ6VXNlcjI5MDA4Mg==",
        "organizations_url": "https://api.github.com/users/leouieda/orgs",
        "received_events_url": "https://api.github.com/users/leouieda/received_events",
        "repos_url": "https://api.github.com/users/leouieda/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/leouieda"
    },
    "comments": 16,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "@chandrex thank you reporting this and sorry for all the trouble! I really appreciate the amount of effort you put in to the issue. That really helps! Welcome to the world of open-source! I hope you'll like it and consider becoming involved :grinning: \r\n\r\nOK, this is a bad crash. It normally shouldn't happen but it's really tricky dealing with C code from Python. One possibility is that Python is finding the wrong version of GMT. Do you have GMT installed from another source (homebrew, fink, etc)? \r\n\r\nCould you try removing the `LD_LIBRARY_PATH` line? That's not usually necessary unless you can't get it to work otherwise. Sorry about this, it should be clearer in the docs and I opened #165 to remind me to deal with this. \r\n\r\nIf that doesn't work, then can you please post the output of `conda list`? That way I can try to see if everything is being installed in the correct version.\r\n\r\nAgain, thanks for detailed issue!\r\n\r\n\r\n\r\n",
            "created_at": "2018-04-20T21:31:12Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-383228103",
            "id": 383228103,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MzIyODEwMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383228103/reactions"
            },
            "updated_at": "2018-04-20T21:31:12Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383228103",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hiya,\r\n\r\nYes I have GMT installed already (5.4.2), which I installed with homebrew. It won't work with or without the `LD_LIBRARY_PATH` (I tried!), but I will remove it anyhow.\r\n\r\nHere is my `conda list`\r\n\r\n<img width=\"729\" alt=\"screen shot 2018-04-23 at 10 07 34\" src=\"https://user-images.githubusercontent.com/37407269/39117205-58541ef8-46de-11e8-8a60-477b892108d8.png\">\r\n<img width=\"579\" alt=\"screen shot 2018-04-23 at 10 07 46\" src=\"https://user-images.githubusercontent.com/37407269/39117206-58701c84-46de-11e8-9e19-cef768da3c7d.png\">\r\n<img width=\"744\" alt=\"screen shot 2018-04-23 at 10 07 59\" src=\"https://user-images.githubusercontent.com/37407269/39117207-588e4ea2-46de-11e8-974d-e3101867d567.png\">\r\n<img width=\"539\" alt=\"screen shot 2018-04-23 at 10 08 21\" src=\"https://user-images.githubusercontent.com/37407269/39117208-58a8f28e-46de-11e8-89f2-dbf6f630ed0e.png\">\r\n\r\nThanks for your help \ud83d\ude01 ",
            "created_at": "2018-04-23T09:10:44Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-383507665",
            "id": 383507665,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MzUwNzY2NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383507665/reactions"
            },
            "updated_at": "2018-04-23T09:10:44Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383507665",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/37407269?v=4",
                "events_url": "https://api.github.com/users/chandrex/events{/privacy}",
                "followers_url": "https://api.github.com/users/chandrex/followers",
                "following_url": "https://api.github.com/users/chandrex/following{/other_user}",
                "gists_url": "https://api.github.com/users/chandrex/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chandrex",
                "id": 37407269,
                "login": "chandrex",
                "node_id": "MDQ6VXNlcjM3NDA3MjY5",
                "organizations_url": "https://api.github.com/users/chandrex/orgs",
                "received_events_url": "https://api.github.com/users/chandrex/received_events",
                "repos_url": "https://api.github.com/users/chandrex/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chandrex/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chandrex/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chandrex"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "OK, here are a few things you can try:\r\n\r\n1. I noticed that your `pandas` and `xarray` were installed by pip. Which indicates that they were pulled in when you installed `gmt-python`. Also, your numpy is a release candidate. We noticed these problems before so we updated the install instructions to match. Could you dele the current environment (`conda env remove -n gmt-python`) and follow [these steps](http://www.gmtpython.xyz/install.html#installing-gmt-and-other-dependencies)?\r\n2. If that doesn't work, then try setting `LD_LIBRARY_PATH` using `export LD_LIBRARY_PATH=$HOME/anaconda3/envs/gmt-python/lib:$LD_LIBRARY_PATH` . This gives anaconda a higher priority. \r\n\r\nI'm working on a better way that we can diagnose these problems (#167). \r\n\r\nAgain, thanks for reporting this! ",
            "created_at": "2018-04-23T23:10:04Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-383750939",
            "id": 383750939,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4Mzc1MDkzOQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383750939/reactions"
            },
            "updated_at": "2018-04-23T23:10:04Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383750939",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@chandrex just to let you know that your issue contributed several changes to the project: #168 #173 #175 #176 and #177 \r\n\r\n#177 introduces a new way to set the path to the GMT shared library. Once, that's incorporated (it will say \"Merged\" on the link) please try deleting your conda environment and following the new instructions that will appear in http://www.gmtpython.xyz/install.html\r\n\r\nAgain, thank you for helping us make things more robust!",
            "created_at": "2018-04-24T05:38:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-383809533",
            "id": 383809533,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4MzgwOTUzMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 1,
                "rocket": 0,
                "total_count": 2,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383809533/reactions"
            },
            "updated_at": "2018-04-24T05:38:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/383809533",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@chandrex please let me know if the new changes work for you. If not we can at least better diagnose the problem.",
            "created_at": "2018-04-24T20:35:09Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-384070994",
            "id": 384070994,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4NDA3MDk5NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/384070994/reactions"
            },
            "updated_at": "2018-04-24T20:35:09Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/384070994",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi @leouieda, alas I have tried everything you suggested and I am still getting the same problem at the final step when I do the gmt.test(), with the failures and segmentation fault. \r\nSteps I took apart from your suggestions:\r\n\u2022 Set up a proper .bashrc (my mac did not have one previously)\r\n\u2022 I thought it could have been a problem with where anaconda was installed, so uninstalled/reinstalled in where $HOME is (it was not there previously)\r\nMaybe I should uninstall my GMT 5 version and see if I can get it working without it? What do you think?",
            "created_at": "2018-04-27T15:59:56Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-385015554",
            "id": 385015554,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4NTAxNTU1NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/385015554/reactions"
            },
            "updated_at": "2018-04-27T15:59:56Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/385015554",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/37407269?v=4",
                "events_url": "https://api.github.com/users/chandrex/events{/privacy}",
                "followers_url": "https://api.github.com/users/chandrex/followers",
                "following_url": "https://api.github.com/users/chandrex/following{/other_user}",
                "gists_url": "https://api.github.com/users/chandrex/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chandrex",
                "id": 37407269,
                "login": "chandrex",
                "node_id": "MDQ6VXNlcjM3NDA3MjY5",
                "organizations_url": "https://api.github.com/users/chandrex/orgs",
                "received_events_url": "https://api.github.com/users/chandrex/received_events",
                "repos_url": "https://api.github.com/users/chandrex/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chandrex/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chandrex/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chandrex"
            }
        },
        {
            "author_association": "MEMBER",
            "body": ":( sorry to hear. You shouldn't have uninstall GMT5. Could you please post the new output of `gmt.test()`? This should let us diagnose the problem now.",
            "created_at": "2018-04-28T01:23:34Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-385129242",
            "id": 385129242,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4NTEyOTI0Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/385129242/reactions"
            },
            "updated_at": "2018-04-28T01:23:34Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/385129242",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi @leouieda here is the screenshot:\r\n\r\n![image](https://user-images.githubusercontent.com/37407269/39474010-b8c40bb0-4d49-11e8-833f-78fc24c83514.png)\r\n\r\nAnd in writing:\r\n\r\nimport gmt\r\ngmt.test()\r\n>=========================== Currently loaded libgmt ============================\r\nbinary dir: /Users/chandra/anaconda3/envs/gmt-python/bin\r\ncores: 4\r\ngrid layout: rows\r\nimage layout:\r\nlibrary path: /Users/chandra/anaconda3/envs/gmt-python/lib/libgmt.dylib\r\npadding: 2\r\nplugin dir: /Users/chandra/anaconda3/envs/gmt-python/lib/gmt/plugins\r\nshare dir: /Users/chandra/anaconda3/envs/gmt-python/share/gmt\r\nversion: 6.0.0\r\n============================= test session starts ==============================\r\nplatform darwin -- Python 3.6.5, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /Users/chandra/anaconda3/envs/gmt-python/bin/python\r\ncachedir: .pytest_cache\r\nMatplotlib: 2.2.2\r\nFreetype: 2.8.1\r\nrootdir: /Users/chandra, inifile:\r\nplugins: mpl-0.9\r\ncollected 132 items\r\n\r\n>anaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/base_plotting.py::gmt.base_plotting.BasePlotting._preprocess PASSED [  0%]\r\nanaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/figure.py::gmt.figure.Figure FAILED [  1%]\r\nanaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py::gmt.clib.core.LibGMT PASSED [  2%]\r\nanaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py::gmt.clib.core.LibGMT._check_dtype_and_dim PASSED [  3%]\r\nanaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py::gmt.clib.core.LibGMT.extract_region gmt-python-session [ERROR]: Long input record (236 bytes) was truncated to first 126 bytes!\r\nFAILED [  3%]\r\nanaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py::gmt.clib.core.LibGMT.grid_to_vfile PASSED [  4%]\r\nanaconda3/envs/gmt-python/lib/python3.6/site-packages/gmt/clib/core.py::gmt.clib.core.LibGMT.log_to_file Segmentation fault: 11",
            "created_at": "2018-05-01T13:19:45Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-385668885",
            "id": 385668885,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4NTY2ODg4NQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/385668885/reactions"
            },
            "updated_at": "2018-05-01T13:19:45Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/385668885",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/37407269?v=4",
                "events_url": "https://api.github.com/users/chandrex/events{/privacy}",
                "followers_url": "https://api.github.com/users/chandrex/followers",
                "following_url": "https://api.github.com/users/chandrex/following{/other_user}",
                "gists_url": "https://api.github.com/users/chandrex/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chandrex",
                "id": 37407269,
                "login": "chandrex",
                "node_id": "MDQ6VXNlcjM3NDA3MjY5",
                "organizations_url": "https://api.github.com/users/chandrex/orgs",
                "received_events_url": "https://api.github.com/users/chandrex/received_events",
                "repos_url": "https://api.github.com/users/chandrex/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chandrex/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chandrex/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chandrex"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi.\r\nI just followed your wiki download/install instructions on mac os 10.10.5 and I get the exact same error:\r\n>>>gmt.test()\r\n...\r\ngmt/clib/core.py::gmt.clib.core.LibGMT.get_libgmt_func PASSED                                                       [  4%]\r\ngmt/clib/core.py::gmt.clib.core.LibGMT.grid_to_vfile PASSED                                                         [  5%]\r\ngmt/clib/core.py::gmt.clib.core.LibGMT.log_to_file Segmentation fault: 11\r\n\r\nMy dependencies (e.g., xarray, pandas) were all installed with conda.\r\nEverything looks good (no complaints) except for the seg fault.\r\n\r\nPlease let me know if anyone makes any progress on solving this.\r\n\r\nCheers!\r\n-Mike",
            "created_at": "2018-05-10T19:34:54Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-388161237",
            "id": 388161237,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4ODE2MTIzNw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/388161237/reactions"
            },
            "updated_at": "2018-05-10T19:34:54Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/388161237",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2146498?v=4",
                "events_url": "https://api.github.com/users/mikehagerty/events{/privacy}",
                "followers_url": "https://api.github.com/users/mikehagerty/followers",
                "following_url": "https://api.github.com/users/mikehagerty/following{/other_user}",
                "gists_url": "https://api.github.com/users/mikehagerty/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mikehagerty",
                "id": 2146498,
                "login": "mikehagerty",
                "node_id": "MDQ6VXNlcjIxNDY0OTg=",
                "organizations_url": "https://api.github.com/users/mikehagerty/orgs",
                "received_events_url": "https://api.github.com/users/mikehagerty/received_events",
                "repos_url": "https://api.github.com/users/mikehagerty/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mikehagerty/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mikehagerty/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mikehagerty"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Hi @mikehagerty and @chandrex this is a very strange failure. I'll try to get my hands on a Mac to investigate. \r\n\r\n@mikehagerty out of curiosity, do you also have GMT5 installed?",
            "created_at": "2018-05-11T01:03:54Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-388229202",
            "id": 388229202,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4ODIyOTIwMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/388229202/reactions"
            },
            "updated_at": "2018-05-11T01:03:54Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/388229202",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "OK, I managed to replicate the issue using Travis CI on #180. It's not a problem with your installation or with the pre-installed GMT5. I'll investigate further to try to get to the bottom of this. \r\n\r\nThanks for bringing this to my attention! It's hard to track these issues when I'm not using a Mac.",
            "created_at": "2018-05-11T02:43:03Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-388243192",
            "id": 388243192,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4ODI0MzE5Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/388243192/reactions"
            },
            "updated_at": "2018-05-11T02:43:03Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/388243192",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi there,\nAny luck on the mac os test fails ?\n\nI just did a clean install of gmt-python and tried the test again:\n\n(gmt-python) mth@Mikes-MBP [~/mth]> python\nPython 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23)\n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import gmt\n>>> gmt.test()\n=============================================== Currently loaded libgmt\n================================================\nbinary dir: /Users/mth/mth/miniconda3/envs/gmt-python/bin\ncores: 4\ngrid layout: rows\nimage layout:\nlibrary path: /Users/mth/mth/miniconda3/envs/gmt-python/lib/libgmt.dylib\npadding: 2\nplugin dir: /Users/mth/mth/miniconda3/envs/gmt-python/lib/gmt/plugins\nshare dir: /Users/mth/mth/miniconda3/envs/gmt-python/share/gmt\nversion: 6.0.0\nusage:  [options] [file_or_dir] [file_or_dir] [...]\n: error: unrecognized arguments: --mpl\n  inifile: None\n  rootdir: /Users/mth/mth\n\nIt seems the usage has changed (?)\n\nCheers!\n-Mike\n\n(gmt-python) mth@Mikes-MBP [~/mth]> conda list gmt\n# packages in environment at /Users/mth/mth/miniconda3/envs/gmt-python:\n#\n# Name                    Version                   Build  Channel\ndcw-gmt                   1.1.3                         0    conda-forge\ngmt                       6.0.0a14        blas_openblas_201\n [blas_openblas]  conda-forge/label/dev\ngmt-python                0+unknown                 <pip>\ngshhg-gmt                 2.3.7                         0    conda-forge\n\nOn Thu, May 10, 2018 at 10:43 PM, Leonardo Uieda <notifications@github.com>\nwrote:\n\n> OK, I managed to replicate the issue using Travis CI on #180\n> <https://github.com/GenericMappingTools/gmt-python/pull/180>. It's not a\n> problem with your installation or with the pre-installed GMT5. I'll\n> investigate further to try to get to the bottom of this.\n>\n> Thanks for bringing this to my attention! It's hard to track these issues\n> when I'm not using a Mac.\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/GenericMappingTools/gmt-python/issues/164#issuecomment-388243192>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/ACDAwkjw0uvHtdeTG851Wq472kl8HlPfks5txPq7gaJpZM4TdsgC>\n> .\n>\n",
            "created_at": "2018-05-21T20:55:22Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-390779752",
            "id": 390779752,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5MDc3OTc1Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/390779752/reactions"
            },
            "updated_at": "2018-05-21T20:55:22Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/390779752",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2146498?v=4",
                "events_url": "https://api.github.com/users/mikehagerty/events{/privacy}",
                "followers_url": "https://api.github.com/users/mikehagerty/followers",
                "following_url": "https://api.github.com/users/mikehagerty/following{/other_user}",
                "gists_url": "https://api.github.com/users/mikehagerty/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mikehagerty",
                "id": 2146498,
                "login": "mikehagerty",
                "node_id": "MDQ6VXNlcjIxNDY0OTg=",
                "organizations_url": "https://api.github.com/users/mikehagerty/orgs",
                "received_events_url": "https://api.github.com/users/mikehagerty/received_events",
                "repos_url": "https://api.github.com/users/mikehagerty/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mikehagerty/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mikehagerty/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mikehagerty"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@mikehagerty sorry, haven't had much time to look into to yet. \r\n\r\nIt seems like you don't have `pytest-mpl` installed. Can you check, please? A lot of the tests compare generated plots using the matplotlib pytest plugin (hurray for duck typing!).",
            "created_at": "2018-05-30T23:31:34Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-393352225",
            "id": 393352225,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5MzM1MjIyNQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/393352225/reactions"
            },
            "updated_at": "2018-05-30T23:31:34Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/393352225",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi Leonardo,\nYou were right that I didn't have pytest-mpl installed, however installing\nit doesn't fix the seg-fault (see below).\n\n\n(gmt-python) mth@Mikes-MBP [~/mth/python_pkgs/gmt-python]> python\nPython 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23)\n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import gmt\n>>> gmt.test()\n=============================================== Currently loaded libgmt\n================================================\nbinary dir: /Users/mth/mth/miniconda3/envs/gmt-python/bin\ncores: 4\ngrid layout: rows\nimage layout:\nlibrary path: /Users/mth/mth/miniconda3/envs/gmt-python/lib/libgmt.dylib\npadding: 2\nplugin dir: /Users/mth/mth/miniconda3/envs/gmt-python/lib/gmt/plugins\nshare dir: /Users/mth/mth/miniconda3/envs/gmt-python/share/gmt\nversion: 6.0.0\n================================================= test session starts\n==================================================\nplatform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 --\n/Users/mth/mth/miniconda3/envs/gmt-python/bin/python\ncachedir: .pytest_cache\nMatplotlib: 2.2.2\nFreetype: 2.8.0\nrootdir: /Users/mth/mth/python_pkgs/gmt-python, inifile:\nplugins: mpl-0.9\ncollected 133 items\n\ngmt/base_plotting.py::gmt.base_plotting.BasePlotting._preprocess PASSED\n                                     [  0%]\ngmt/figure.py::gmt.figure.Figure gmt-python-session [ERROR]: Long input\nrecord (246 bytes) was truncated to first 126 bytes!\nPASSED\n     [  1%]\ngmt/clib/core.py::gmt.clib.core.LibGMT PASSED\n                                     [  2%]\ngmt/clib/core.py::gmt.clib.core.LibGMT._check_dtype_and_dim PASSED\n                                      [  3%]\ngmt/clib/core.py::gmt.clib.core.LibGMT.extract_region gmt-python-session\n[ERROR]: Long input record (236 bytes) was truncated to first 126 bytes!\ngmt-python-session [ERROR]: Long input record (247 bytes) was truncated to\nfirst 126 bytes!\ngmt-python-session [ERROR]: Long input record (239 bytes) was truncated to\nfirst 126 bytes!\nPASSED                                                     [  3%]\ngmt/clib/core.py::gmt.clib.core.LibGMT.get_libgmt_func PASSED\n                                     [  4%]\ngmt/clib/core.py::gmt.clib.core.LibGMT.grid_to_vfile FAILED\n                                     [  5%]\ngmt/clib/core.py::gmt.clib.core.LibGMT.log_to_file *Segmentation fault:* 11\n(gmt-python) mth@Mikes-MBP [~/mth/python_pkgs/gmt-python]>\n\n\nUpdate: Here's a quick test:\n\nimport gmt\n\nwith gmt.clib.LibGMT() as lib:\n     mode = lib.get_constant('GMT_MODULE_CMD')\n     with lib.log_to_file() as logfile:\n         call_module = lib.get_libgmt_func('GMT_Call_Module')\n         print(\"MTH: mode=\", mode)\n         print(\"MTH: session=\", lib.current_session)\n         print(\"MTH: type(call_module)=\", type(call_module))\n         status = call_module(lib.current_session, 'info'.encode(),\n                              mode, 'bogus-file.bla'.encode())\n         print(\"MTH: status=\", status)\n\nIt seems to be dying when trying to follow the pointer to call_module().\nSo maybe it's a ctypes issue ?\n\nMTH: mode= 0\nMTH: session= 140533251525120\nMTH: type(call_module)= <class 'ctypes.CDLL.__init__.<locals>._FuncPtr'>\nSegmentation fault: 11\n\nCheers!\n-Mike\n\n\nOn Wed, May 30, 2018 at 7:31 PM, Leonardo Uieda <notifications@github.com>\nwrote:\n\n> @mikehagerty <https://github.com/mikehagerty> sorry, haven't had much\n> time to look into to yet.\n>\n> It seems like you don't have pytest-mpl installed. Can you check, please?\n> A lot of the tests compare generated plots using the matplotlib pytest\n> plugin (hurray for duck typing!).\n>\n> \u2014\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/GenericMappingTools/gmt-python/issues/164#issuecomment-393352225>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/ACDAwqoKhLMo0NC00mHPIeZM92j66ivfks5t3yvYgaJpZM4TdsgC>\n> .\n>\n",
            "created_at": "2018-06-01T18:58:53Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-393978551",
            "id": 393978551,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5Mzk3ODU1MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/393978551/reactions"
            },
            "updated_at": "2018-06-01T18:58:53Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/393978551",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2146498?v=4",
                "events_url": "https://api.github.com/users/mikehagerty/events{/privacy}",
                "followers_url": "https://api.github.com/users/mikehagerty/followers",
                "following_url": "https://api.github.com/users/mikehagerty/following{/other_user}",
                "gists_url": "https://api.github.com/users/mikehagerty/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mikehagerty",
                "id": 2146498,
                "login": "mikehagerty",
                "node_id": "MDQ6VXNlcjIxNDY0OTg=",
                "organizations_url": "https://api.github.com/users/mikehagerty/orgs",
                "received_events_url": "https://api.github.com/users/mikehagerty/received_events",
                "repos_url": "https://api.github.com/users/mikehagerty/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mikehagerty/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mikehagerty/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mikehagerty"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@mikehagerty thanks for the info! \r\n\r\nI suspect that it's the log file actually but it's a bit tough to debug when TravisCI is not cooperating. I haven't found a good fix for that yet so I might just disable it for now. This is used to get the error messages printed by GMT. It's helpful but not vital for now.",
            "created_at": "2018-06-01T20:48:09Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-394004862",
            "id": 394004862,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5NDAwNDg2Mg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/394004862/reactions"
            },
            "updated_at": "2018-06-01T20:48:09Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/394004862",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Good news everyone @chandrex @mikehagerty! :tada: :cake: :balloon: \r\n\r\nI finally managed to fix this issue in #188! It was a long struggle and I still have no idea why the fault was happening. But I replaced the code that was causing the problem with something better and the fault went away. Things should be working smoothly on Mac now.\r\n\r\nCould you please give it a try and report back? Thank you for all the information you all provided and sorry for long delay. :rocket: ",
            "created_at": "2018-06-16T04:38:42Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164#issuecomment-397786231",
            "id": 397786231,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5Nzc4NjIzMQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/397786231/reactions"
            },
            "updated_at": "2018-06-16T04:38:42Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/397786231",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/290082?v=4",
                "events_url": "https://api.github.com/users/leouieda/events{/privacy}",
                "followers_url": "https://api.github.com/users/leouieda/followers",
                "following_url": "https://api.github.com/users/leouieda/following{/other_user}",
                "gists_url": "https://api.github.com/users/leouieda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/leouieda",
                "id": 290082,
                "login": "leouieda",
                "node_id": "MDQ6VXNlcjI5MDA4Mg==",
                "organizations_url": "https://api.github.com/users/leouieda/orgs",
                "received_events_url": "https://api.github.com/users/leouieda/received_events",
                "repos_url": "https://api.github.com/users/leouieda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/leouieda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/leouieda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/leouieda"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164/comments",
    "created_at": "2018-04-20T15:53:10Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/164",
    "id": 316321321,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzMTYzMjEzMjE=",
    "number": 164,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164/timeline",
    "title": "Segfault on MacOS caused by LibGMT.log_to_file",
    "updated_at": "2018-06-16T04:38:42Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/164",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/37407269?v=4",
        "events_url": "https://api.github.com/users/chandrex/events{/privacy}",
        "followers_url": "https://api.github.com/users/chandrex/followers",
        "following_url": "https://api.github.com/users/chandrex/following{/other_user}",
        "gists_url": "https://api.github.com/users/chandrex/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/chandrex",
        "id": 37407269,
        "login": "chandrex",
        "node_id": "MDQ6VXNlcjM3NDA3MjY5",
        "organizations_url": "https://api.github.com/users/chandrex/orgs",
        "received_events_url": "https://api.github.com/users/chandrex/received_events",
        "repos_url": "https://api.github.com/users/chandrex/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/chandrex/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chandrex/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/chandrex"
    }
}