{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\nOn macOS, it seems like GMT is broken with GEOS 3.10 (release 22 Oct to conda-forge https://github.com/conda-forge/geos-feedstock/pull/61). See recent failure on `cache_data.yml` at https://github.com/GenericMappingTools/pygmt/runs/4059892997?check_suite_focus=true#step:6:8.\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nfrom pygmt.helpers.testing import download_test_data\r\ndownload_test_data()\r\n```\r\n\r\n**Full error message**\r\n\r\n```python-traceback\r\ndyld: Library not loaded: @rpath/libgeos_c.1.dylib\r\n  Referenced from: /Users/runner/miniconda3/envs/test/lib/libgmt.6.2.0.dylib\r\n  Reason: Incompatible library version: libgmt.6.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"/Users/runner/work/pygmt/pygmt/pygmt/__init__.py\", line 70, in <module>\r\n    _begin()\r\n  File \"/Users/runner/work/pygmt/pygmt/pygmt/session_management.py\", line 16, in begin\r\n    with Session() as lib:\r\n  File \"/Users/runner/work/pygmt/pygmt/pygmt/clib/session.py\", line 183, in __enter__\r\n    self.create(\"pygmt-session\")\r\n  File \"/Users/runner/work/pygmt/pygmt/pygmt/clib/session.py\", line 329, in create\r\n    c_create_session = self.get_libgmt_func(\r\n  File \"/Users/runner/work/pygmt/pygmt/pygmt/clib/session.py\", line 281, in get_libgmt_func\r\n    self._libgmt = load_libgmt()\r\n  File \"/Users/runner/work/pygmt/pygmt/pygmt/clib/loading.py\", line 59, in load_libgmt\r\n    raise GMTCLibNotFoundError(\"\\n\".join(error_msg))\r\npygmt.exceptions.GMTCLibNotFoundError: Error loading GMT shared library at 'libgmt.dylib'.\r\ndlopen(libgmt.dylib, 6): Library not loaded: @rpath/libgeos_c.1.dylib\r\n  Referenced from: /Users/runner/miniconda3/envs/test/lib/libgmt.6.2.0.dylib\r\n  Reason: Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0\r\nError: Process completed with exit code 1.\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\npygmt v0.5.0\r\n```\r\n\r\nI don't have a macOS computer to test or debug, but workaround may be to downgrade to `geos=5.9` for now using `conda install -c conda-forge geos=3.9`. Feel free to move this issue to upstream GMT if it's better.\r\n\r\nEdit: Or maybe it's an issue on the GEOS side :slightly_smiling_face: There is an ongoing migration for GEOS 3.10 on conda-forge, see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2051 and https://conda-forge.org/status/#geos3100\r\n\r\nEdit2: A user has reported similar problem on the forum at https://forum.generic-mapping-tools.org/t/import-pygmt-error-after-jupyterlab-installation/2117/4. Might be quite serious...",
    "closed_at": "2021-11-03T14:32:24Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 17,
    "comments_content": [
        {
            "author_association": "MEMBER",
            "body": "A few notes based on some trials on macOS:\r\n- The problem likely an issue with GMT, because geos is a dependency through gdal, which works as expected through `conda create --name gdal; conda activate gdal; conda install -c conda-forge gdal`.\r\n- `conda install -c conda-forge geos=3.9` solves the problem.\r\n- `conda create --name gmt-test; conda activate gmt-test; conda install -c conda-forge gmt; gmt --version` reproduces the problem without needing to go through PyGMT.\r\n\r\nMy guess is that something is wrong with the gmt conda recipe because building gmt from source works fine even when using the conda-forge version of gdal and geos dependencies. ",
            "created_at": "2021-11-01T16:36:19Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956390575",
            "id": 956390575,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845AVyv",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 1,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956390575/reactions"
            },
            "updated_at": "2021-11-01T16:36:19Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956390575",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Since this breaks our macOS CI workflows, I agree that it's a serious issue.\r\n\r\nHere's the version information reported by otool for geos 3.10:\r\n```\r\n\t@rpath/libgeos_c.1.dylib (compatibility version 1.0.0, current version 1.16.0)\r\n\t@rpath/libgeos.3.10.0.dylib (compatibility version 3.10.0, current version 3.10.0)\r\n```\r\nand for geos 3.9:\r\n```\r\n\t@rpath/libgeos_c.1.dylib (compatibility version 16.0.0, current version 16.2.0)\r\n\t@rpath/libgeos-3.9.1.dylib (compatibility version 0.0.0, current version 0.0.0)\r\n```\r\nI am not that familiar with these libraries. @PaulWessel, do you know if there's a way for us to adapt for the version jump or whether we should find a way to report this to the geos devs?",
            "created_at": "2021-11-01T22:41:30Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956784551",
            "id": 956784551,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845B1-n",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956784551/reactions"
            },
            "updated_at": "2021-11-01T22:41:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956784551",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I saw that the conda-forge geos-feedstock changed to using `cmake` instead of `autotools` (see https://github.com/conda-forge/geos-feedstock/issues/54 and https://github.com/conda-forge/geos-feedstock/pull/61#issuecomment-948140127). Not sure if that had an impact, at least I didn't notice anything out of hand at https://github.com/conda-forge/geos-feedstock/pull/61/files#diff-d10439659fe44156d9eac347f9e9eb6992e5b516d0f7e86df061c8273397fd7d.\r\n\r\nAlso not clear to me whether the exact problem is at, is it 1) GMT, 2) the conda-forge geos-feedstock or 3) geos? Afraid that I won't be of much help troubleshooting since I don't have a Mac computer either. Most I could help with is to pin the [`gmt-feedstock`](https://github.com/conda-forge/gmt-feedstock) to geos < 3.10 until this is worked out.\r\n\r\nEdit: I found this old thread at https://trac.osgeo.org/geos/ticket/669#comment:8 which might explain the weird change in  versioning from 16.2.0 to 1.16.0 related to using `cmake`.",
            "created_at": "2021-11-01T23:06:30Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956834230",
            "id": 956834230,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845CCG2",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956834230/reactions"
            },
            "updated_at": "2021-11-02T21:40:09Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956834230",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "GMT only started using geos when @joa-quim added it as a conditional library for buffering in **gmtspatial**, if I recall correctly.  So that is the only place.  Help me understand the problem: So libgmt is built with GDAL and GEOS support and it gets the latest version the distribution provides.  Then, when it is loaded in pyGMT there is a conflict with  the geos library? How are the two geos libraries different on the same system? You are building GMT on that system, no?",
            "created_at": "2021-11-01T23:46:21Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956913863",
            "id": 956913863,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845CVjH",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956913863/reactions"
            },
            "updated_at": "2021-11-01T23:46:21Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956913863",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "There are news of GEOS 3.10 breaking GDAL in Julia as well. I'm having no problems on Windows but probably because I rebuilt GDAL after updating to GEOS 3.10",
            "created_at": "2021-11-01T23:56:00Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956931509",
            "id": 956931509,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845CZ21",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956931509/reactions"
            },
            "updated_at": "2021-11-01T23:56:00Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956931509",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/537321?v=4",
                "events_url": "https://api.github.com/users/joa-quim/events{/privacy}",
                "followers_url": "https://api.github.com/users/joa-quim/followers",
                "following_url": "https://api.github.com/users/joa-quim/following{/other_user}",
                "gists_url": "https://api.github.com/users/joa-quim/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/joa-quim",
                "id": 537321,
                "login": "joa-quim",
                "node_id": "MDQ6VXNlcjUzNzMyMQ==",
                "organizations_url": "https://api.github.com/users/joa-quim/orgs",
                "received_events_url": "https://api.github.com/users/joa-quim/received_events",
                "repos_url": "https://api.github.com/users/joa-quim/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/joa-quim/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/joa-quim/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/joa-quim"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> GMT only started using geos when @joa-quim added it as a conditional library for buffering in **gmtspatial**, if I recall correctly. So that is the only place. Help me understand the problem: So libgmt is built with GDAL and GEOS support and it gets the latest version the distribution provides. Then, when it is loaded in pyGMT there is a conflict with the geos library? How are the two geos libraries different on the same system? You are building GMT on that system, no?\r\n\r\nThe two GEOS libraries are in separate virtual environments on the same system. In one virtual environment, I installed GDAL with GEOS 3.10 using conda-forge and built gmt from source (no problems). In another, I installed GDAL with GEOS 3.9 and GMT 6.2 using conda-forge (no problems). In a third, I installed GDAL and GEOS 3.10 and GMT 6.2 using conda-forge (`gmt --version` did not work with the error `Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0`).",
            "created_at": "2021-11-02T00:05:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956949238",
            "id": 956949238,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845CeL2",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956949238/reactions"
            },
            "updated_at": "2021-11-02T00:05:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956949238",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": ">  In a third, I installed GDAL and GEOS 3.10 and GMT 6.2 using conda-forge (`gmt --version` did not work with the error `Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0`).\r\n\r\nSo when you install GMT 6.2 using conda-forge you get a build using GEOS 3.9 which does not exist in that environment?  ",
            "created_at": "2021-11-02T00:11:49Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956961635",
            "id": 956961635,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845ChNj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956961635/reactions"
            },
            "updated_at": "2021-11-02T00:11:49Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956961635",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> > In a third, I installed GDAL and GEOS 3.10 and GMT 6.2 using conda-forge (`gmt --version` did not work with the error `Incompatible library version: libgmt.dylib requires version 16.0.0 or later, but libgeos_c.1.dylib provides version 1.0.0`).\r\n> \r\n> So when you install GMT 6.2 using conda-forge you get a build using GEOS 3.9 which does not exist in that environment?\r\n\r\nI'm sorry, but I do not fully understand your question. GEOS 3.9 does not exist in that environment. I do not know whether there's anything about the GMT 6.2 build that specifies that it must be GEOS 3.9 such that GEOS 3.10 would not suffice.",
            "created_at": "2021-11-02T00:22:18Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-956980821",
            "id": 956980821,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845Cl5V",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956980821/reactions"
            },
            "updated_at": "2021-11-02T00:22:18Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/956980821",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "OK, so, there is nothing in GMT Cmake that says anything about what version GEOS must be.  What does it say it finds when it is running Cmake configure? I.e.\r\n\r\n```\r\n...\r\n*  GEOS library               : /opt/local/lib/libgeos_c.dylib\r\n*  GEOS include dir           : /opt/local/include\r\n...\r\n```\r\n\r\nwhat does it say for your failing case?",
            "created_at": "2021-11-02T00:40:08Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-957001754",
            "id": 957001754,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845CrAa",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/957001754/reactions"
            },
            "updated_at": "2021-11-02T00:40:08Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/957001754",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> OK, so, there is nothing in GMT Cmake that says anything about what version GEOS must be. What does it say it finds when it is running Cmake configure? I.e.\r\n> \r\n> ```\r\n> ...\r\n> *  GEOS library               : /opt/local/lib/libgeos_c.dylib\r\n> *  GEOS include dir           : /opt/local/include\r\n> ...\r\n> ```\r\n> \r\n> what does it say for your failing case?\r\n\r\nI do not know of a way to get this information, since conda distributes a built version and the CI logs have expired. @weiji14, do you think it could be helpful to [rerender the gmt feedstock](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks)? This situation may meet the criteria 'updates to the build matrix' in their guides for [when to rerender](https://conda-forge.org/docs/maintainer/updating_pkgs.html#when-to-rerender).\r\n\r\nAlso, I think we should transfer this issue to the gmt-feedstock repository since this seems to be a conda-forge specific problem (I can build GMT fine on macOS with GEOS 3.10.0).",
            "created_at": "2021-11-02T14:57:57Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-957758728",
            "id": 957758728,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845Fj0I",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/957758728/reactions"
            },
            "updated_at": "2021-11-02T14:57:57Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/957758728",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/14077947?v=4",
                "events_url": "https://api.github.com/users/maxrjones/events{/privacy}",
                "followers_url": "https://api.github.com/users/maxrjones/followers",
                "following_url": "https://api.github.com/users/maxrjones/following{/other_user}",
                "gists_url": "https://api.github.com/users/maxrjones/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/maxrjones",
                "id": 14077947,
                "login": "maxrjones",
                "node_id": "MDQ6VXNlcjE0MDc3OTQ3",
                "organizations_url": "https://api.github.com/users/maxrjones/orgs",
                "received_events_url": "https://api.github.com/users/maxrjones/received_events",
                "repos_url": "https://api.github.com/users/maxrjones/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/maxrjones/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/maxrjones/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/maxrjones"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "OK, so basically conda built a GMT library using 3.9 but on your system there is no 3.9.\r\n",
            "created_at": "2021-11-02T18:56:29Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-958063415",
            "id": 958063415,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845GuM3",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/958063415/reactions"
            },
            "updated_at": "2021-11-02T18:56:29Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/958063415",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/26473567?v=4",
                "events_url": "https://api.github.com/users/PaulWessel/events{/privacy}",
                "followers_url": "https://api.github.com/users/PaulWessel/followers",
                "following_url": "https://api.github.com/users/PaulWessel/following{/other_user}",
                "gists_url": "https://api.github.com/users/PaulWessel/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/PaulWessel",
                "id": 26473567,
                "login": "PaulWessel",
                "node_id": "MDQ6VXNlcjI2NDczNTY3",
                "organizations_url": "https://api.github.com/users/PaulWessel/orgs",
                "received_events_url": "https://api.github.com/users/PaulWessel/received_events",
                "repos_url": "https://api.github.com/users/PaulWessel/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/PaulWessel/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/PaulWessel/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/PaulWessel"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> I do not know of a way to get this information, since conda distributes a built version and the CI logs have expired. @weiji14, do you think it could be helpful to [rerender the gmt feedstock](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks)? This situation may meet the criteria 'updates to the build matrix' in their guides for [when to rerender](https://conda-forge.org/docs/maintainer/updating_pkgs.html#when-to-rerender).\r\n\r\nOk, I'll try to rerender the feedstock and see if it helps. Do you think GEOS should be listed as an explicit runtime dependency at https://github.com/conda-forge/gmt-feedstock/blob/0455a1e5346c23c7bde78c6f0652a75966ac1dab/recipe/meta.yaml#L33-L48? Or should we just treat it as a one-off situation and hope things don't break in the future?\r\n\r\n> Also, I think we should transfer this issue to the gmt-feedstock repository since this seems to be a conda-forge specific problem (I can build GMT fine on macOS with GEOS 3.10.0).\r\n\r\nI can't transfer the issue because the gmt-feedstock repo isn't in the GenericMappingTools organization. So let's just keep it here for now.\r\n",
            "created_at": "2021-11-02T21:37:07Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-958186106",
            "id": 958186106,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845HMJ6",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/958186106/reactions"
            },
            "updated_at": "2021-11-02T21:37:07Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/958186106",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Here's the version information reported by otool for geos 3.10:\r\n> \r\n> \t@rpath/libgeos_c.1.dylib (compatibility version 1.0.0, current version 1.16.0)\r\n> \t@rpath/libgeos.3.10.0.dylib (compatibility version 3.10.0, current version 3.10.0)\r\n> and for geos 3.9:\r\n> \r\n> \t@rpath/libgeos_c.1.dylib (compatibility version 16.0.0, current version 16.2.0)\r\n> \t@rpath/libgeos-3.9.1.dylib (compatibility version 0.0.0, current version 0.0.0)\r\n\r\nBecause the changes of the geos version scheme (`0.0.0` -> `3.10.0`, and `16.2.0` -> `1.16.0`), any packages that link to the geos package need to be rebuilt.\r\n\r\n> \u200bEdit: Or maybe it's an issue on the GEOS side \ud83d\ude42 There is an ongoing migration for GEOS 3.10 on conda-forge, see [conda-forge/conda-forge-pinning-feedstock#2051](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2051) and [conda-forge.org/status/#geos3100](https://conda-forge.org/status/#geos3100)\r\n\r\nBecause geos is not listed as a runtime dependency, the conda-forge's geos3100 migration didn't trigger a new build for GMT. I believe https://github.com/conda-forge/gmt-feedstock/pull/169 will fix the issue",
            "created_at": "2021-11-03T04:46:14Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-958653075",
            "id": 958653075,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845I-KT",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/958653075/reactions"
            },
            "updated_at": "2021-11-03T04:46:14Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/958653075",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "https://github.com/conda-forge/gmt-feedstock/pull/169 fixed the issue. All tests pass now.",
            "created_at": "2021-11-03T14:32:24Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-959258942",
            "id": 959258942,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845LSE-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/959258942/reactions"
            },
            "updated_at": "2021-11-03T14:32:24Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/959258942",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "NONE",
            "body": "As I reported on the GMT discussion forum, the new version of `conda-forge/gmt-feedstock` fixed the problem that I had running PyGMT on MacOS. Thanks for the fast work!",
            "created_at": "2021-11-04T17:13:11Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-961248164",
            "id": 961248164,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845S3uk",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/961248164/reactions"
            },
            "updated_at": "2021-11-04T17:13:11Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/961248164",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/7253576?v=4",
                "events_url": "https://api.github.com/users/EJFielding/events{/privacy}",
                "followers_url": "https://api.github.com/users/EJFielding/followers",
                "following_url": "https://api.github.com/users/EJFielding/following{/other_user}",
                "gists_url": "https://api.github.com/users/EJFielding/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/EJFielding",
                "id": 7253576,
                "login": "EJFielding",
                "node_id": "MDQ6VXNlcjcyNTM1NzY=",
                "organizations_url": "https://api.github.com/users/EJFielding/orgs",
                "received_events_url": "https://api.github.com/users/EJFielding/received_events",
                "repos_url": "https://api.github.com/users/EJFielding/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/EJFielding/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/EJFielding/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/EJFielding"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "@weiji14 It reminds me that we need to apply the same patch to the devel branch of the feedstock. Do you want to do it?",
            "created_at": "2021-11-05T01:04:51Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-961549088",
            "id": 961549088,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845UBMg",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/961549088/reactions"
            },
            "updated_at": "2021-11-05T01:04:51Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/961549088",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> @weiji14 It reminds me that we need to apply the same patch to the devel branch of the feedstock. Do you want to do it?\r\n\r\nIt's been rebuilt already at https://github.com/conda-forge/gmt-feedstock/pull/170. Same with the v5.x branch. But looks like the runtime dependency wasn't added to recipe/meta.yaml, so I'll add it in.",
            "created_at": "2021-11-05T01:59:42Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600#issuecomment-961568385",
            "id": 961568385,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
            "node_id": "IC_kwDOBRZfO845UF6B",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/961568385/reactions"
            },
            "updated_at": "2021-11-05T02:01:30Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/961568385",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
                "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
                "followers_url": "https://api.github.com/users/weiji14/followers",
                "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
                "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/weiji14",
                "id": 23487320,
                "login": "weiji14",
                "node_id": "MDQ6VXNlcjIzNDg3MzIw",
                "organizations_url": "https://api.github.com/users/weiji14/orgs",
                "received_events_url": "https://api.github.com/users/weiji14/received_events",
                "repos_url": "https://api.github.com/users/weiji14/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/weiji14"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600/comments",
    "created_at": "2021-10-31T23:52:09Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/1600",
    "id": 1040614871,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": "2022-03-15T23:17:52Z",
        "closed_issues": 174,
        "created_at": "2021-06-23T03:22:20Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/9",
        "id": 6880166,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/9/labels",
        "node_id": "MDk6TWlsZXN0b25lNjg4MDE2Ng==",
        "number": 9,
        "open_issues": 0,
        "state": "closed",
        "title": "0.6.0",
        "updated_at": "2022-03-15T23:17:52Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/9"
    },
    "node_id": "I_kwDOBRZfO84-BoXX",
    "number": 1600,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600/timeline",
    "title": "GEOS 3.10.0 breaks GMT on macOS",
    "updated_at": "2021-11-05T02:01:30Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/1600",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/23487320?v=4",
        "events_url": "https://api.github.com/users/weiji14/events{/privacy}",
        "followers_url": "https://api.github.com/users/weiji14/followers",
        "following_url": "https://api.github.com/users/weiji14/following{/other_user}",
        "gists_url": "https://api.github.com/users/weiji14/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/weiji14",
        "id": 23487320,
        "login": "weiji14",
        "node_id": "MDQ6VXNlcjIzNDg3MzIw",
        "organizations_url": "https://api.github.com/users/weiji14/orgs",
        "received_events_url": "https://api.github.com/users/weiji14/received_events",
        "repos_url": "https://api.github.com/users/weiji14/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/weiji14/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/weiji14/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/weiji14"
    }
}