{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\n\r\nFresh install of GMT using the bundle for MacOS (my system is Catalina, 10.15.7). Successfully tested on a simple example. \r\nEnvironnement variables set:\r\necho $GMTHOME\r\n/Applications/GMT-6.1.1.app/Contents/Resources\r\necho $GMT_LIBRARY_PATH\r\n/Applications/GMT-6.1.1.app/Contents/Resources/lib\r\n\r\npygmt installed using pip (not conda) in a python3 venv. \r\npython3 --version\r\nPython 3.8.3\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\npygmt.show_versions()\r\npygmt.test()\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"test2.py\", line 1, in <module>\r\n    import pygmt\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/__init__.py\", line 32, in <module>\r\n    _begin()\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/session_management.py\", line 16, in begin\r\n    with Session() as lib:\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py\", line 183, in __enter__\r\n    self.create(\"pygmt-session\")\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py\", line 333, in create\r\n    c_create_session = self.get_libgmt_func(\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py\", line 284, in get_libgmt_func\r\n    self._libgmt = load_libgmt()\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/loading.py\", line 46, in load_libgmt\r\n    raise GMTCLibNotFoundError(\r\npygmt.exceptions.GMTCLibNotFoundError: Error loading the GMT shared library '/Applications/GMT-6.1.1.app/Contents/Resources/lib/libgmt.dylib':\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/__init__.py\", line 32, in <module>\r\n    _begin()\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/session_management.py\", line 16, in begin\r\n    with Session() as lib:\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py\", line 183, in __enter__\r\n    self.create(\"pygmt-session\")\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py\", line 333, in create\r\n    c_create_session = self.get_libgmt_func(\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/session.py\", line 284, in get_libgmt_func\r\n    self._libgmt = load_libgmt()\r\n  File \"/Users/stephane/Tools/PyEnvs/GMT/lib/python3.8/site-packages/pygmt/clib/loading.py\", line 46, in load_libgmt\r\n    raise GMTCLibNotFoundError(\r\npygmt.exceptions.GMTCLibNotFoundError: Error loading the GMT shared library '/Applications/GMT-6.1.1.app/Contents/Resources/lib/libgmt.dylib':\r\n```\r\n",
    "closed_at": "2020-12-25T05:12:44Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 3,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/master/CODE_OF_CONDUCT.md).\n",
            "created_at": "2020-12-09T11:09:37Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/722#issuecomment-741702781",
            "id": 741702781,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc0MTcwMjc4MQ==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/741702781/reactions"
            },
            "updated_at": "2020-12-09T11:09:37Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/741702781",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Yes, it's a known issue of the GMT macOS bundle. Please see https://github.com/GenericMappingTools/gmt/issues/1930 for discussions.\r\n\r\nWe recommend you to install pygmt and gmt using `conda`. If you still prefer to use the macOS bundle, you may try the \"solution\" in this comment https://github.com/GenericMappingTools/gmt/issues/1930#issuecomment-698683500.\r\n\r\n",
            "created_at": "2020-12-09T14:12:14Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/722#issuecomment-741795913",
            "id": 741795913,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc0MTc5NTkxMw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/741795913/reactions"
            },
            "updated_at": "2020-12-09T14:12:14Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/741795913",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Closing the issue as it's a duplicate of upstream bug https://github.com/GenericMappingTools/gmt/issues/1930",
            "created_at": "2020-12-25T05:12:43Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/722#issuecomment-751172922",
            "id": 751172922,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722",
            "node_id": "MDEyOklzc3VlQ29tbWVudDc1MTE3MjkyMg==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/751172922/reactions"
            },
            "updated_at": "2020-12-25T05:12:43Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/751172922",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722/comments",
    "created_at": "2020-12-09T11:09:35Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/722",
    "id": 760234654,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "e8ff6b",
            "default": false,
            "description": "Bug or missing feature of upstream core GMT",
            "id": 2059525605,
            "name": "upstream",
            "node_id": "MDU6TGFiZWwyMDU5NTI1NjA1",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/upstream"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3NjAyMzQ2NTQ=",
    "number": 722,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722/timeline",
    "title": "Problem installing on MacOS",
    "updated_at": "2020-12-25T05:12:44Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/722",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10595694?v=4",
        "events_url": "https://api.github.com/users/labrosse/events{/privacy}",
        "followers_url": "https://api.github.com/users/labrosse/followers",
        "following_url": "https://api.github.com/users/labrosse/following{/other_user}",
        "gists_url": "https://api.github.com/users/labrosse/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/labrosse",
        "id": 10595694,
        "login": "labrosse",
        "node_id": "MDQ6VXNlcjEwNTk1Njk0",
        "organizations_url": "https://api.github.com/users/labrosse/orgs",
        "received_events_url": "https://api.github.com/users/labrosse/received_events",
        "repos_url": "https://api.github.com/users/labrosse/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/labrosse/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/labrosse/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/labrosse"
    }
}