{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Description of the problem**\r\n\r\n<!-- Please be as detailed as you can when describing an issue. The more information we have, the easier it will be for us to track this down. -->\r\n\r\n\r\n```python\r\nimport pygmt\r\nregion=[77, 79, 29.5, 30.5]\r\nfig= pygmt.Figure()\r\nctopo=pygmt.makecpt(cmap=\"himalaya.cpt\")\r\ngrid = pygmt.datasets.load_earth_relief(resolution='01s', region=region)\r\nKWARGS = dict(grid=grid,region=region, projection='M4i',frame=True, E=300)\r\nfig.grdimage(**KWARGS,cmap=ctopo,shading=True)\r\nfig.show()\r\n```\r\nGiving me the following error\r\n```\r\nTraceback (most recent call last):\r\n  File \"<ipython-input-11-78e4c4e19ed9>\", line 1, in <module>\r\n    fig.grdimage(**KWARGS,cmap=ctopo,shading=True)\r\n  File \"C:\\ProgramData\\Anaconda3\\envs\\roses\\lib\\site-packages\\pygmt\\helpers\\decorators.py\", line 270, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"C:\\ProgramData\\Anaconda3\\envs\\roses\\lib\\site-packages\\pygmt\\helpers\\decorators.py\", line 411, in new_module\r\n    return module_func(*args, **kwargs)\r\n  File \"C:\\ProgramData\\Anaconda3\\envs\\roses\\lib\\site-packages\\pygmt\\base_plotting.py\", line 485, in grdimage\r\n    lib.call_module(\"grdimage\", arg_str)\r\n  File \"C:\\ProgramData\\Anaconda3\\envs\\roses\\lib\\site-packages\\pygmt\\clib\\session.py\", line 503, in call_module\r\n    self.session_pointer, module.encode(), mode, args.encode()\r\nOSError: exception: access violation reading 0x000001E880146FBC\r\n```\r\n\r\n\r\n\r\n\r\n\r\nI am using conda environment in Windows\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.2.1\r\nSystem information:\r\n  python: 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:02:53) [MSC v.1916 64 bit (AMD64)]\r\n  executable: C:\\ProgramData\\Anaconda3\\envs\\roses\\python.exe\r\n  machine: Windows-10-10.0.19041-SP0\r\nDependency information:\r\n  numpy: 1.19.4\r\n  pandas: 1.1.4\r\n  xarray: 0.16.1\r\n  netCDF4: 1.5.4\r\n  packaging: 20.4\r\n  ghostscript: 9.53.3\r\n  gmt: 6.1.1\r\nGMT library information:\r\n  binary dir: C:/ProgramData/Anaconda3/envs/roses\r\n  cores: 4\r\n  grid layout: rows\r\n  library path: C:/ProgramData/Anaconda3/envs/roses/Library/bin/gmt.dll\r\n  padding: 2\r\n  plugin dir: C:/ProgramData/Anaconda3/envs/roses/Library/bin/gmt_plugins\r\n  share dir: c:/programs/gmt5/share\r\n  version: 6.1.1\r\n```",
    "closed_at": "2021-03-18T04:43:56Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 3,
    "comments_content": [
        {
            "author_association": "NONE",
            "body": "\ud83d\udc4b Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/pygmt/blob/master/CODE_OF_CONDUCT.md).\n",
            "created_at": "2020-12-07T08:52:41Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/717#issuecomment-739773583",
            "id": 739773583,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717",
            "node_id": "MDEyOklzc3VlQ29tbWVudDczOTc3MzU4Mw==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/739773583/reactions"
            },
            "updated_at": "2020-12-07T08:52:41Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/739773583",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/in/4141?v=4",
                "events_url": "https://api.github.com/users/welcome%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/welcome%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/welcome%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/welcome%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/welcome",
                "id": 30606887,
                "login": "welcome[bot]",
                "node_id": "MDM6Qm90MzA2MDY4ODc=",
                "organizations_url": "https://api.github.com/users/welcome%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/welcome%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/welcome%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/welcome%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/welcome%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/welcome%5Bbot%5D"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Yes, we notice similar crashes in our CI testings. It's still unclear to us why and where it happens, as none of us is developing PyGMT under Windows. \r\n\r\nYou have two options:\r\n\r\n1. Re-run the script again. Sometimes it crashes, but sometimes it works well\r\n2. Directly use the GMT remote file, i.e., `KWARGS = dict(grid=\"@earth_relief_01s\",region=region, projection='M4i',frame=True, E=300)`, instead of using the `pygmt.datasets.load_earth_relief`, which loads the grid into memory.",
            "created_at": "2020-12-07T14:55:35Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/717#issuecomment-739969038",
            "id": 739969038,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717",
            "node_id": "MDEyOklzc3VlQ29tbWVudDczOTk2OTAzOA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/739969038/reactions"
            },
            "updated_at": "2020-12-07T14:55:35Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/739969038",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I'd like to close the issue, because:\r\n\r\n1. We already know that PyGMT sometimes crashes on Windows\r\n2. We don't have any Windows developers to track the crashes\r\n3. There are most likely issues of GMT, not PyGMT.",
            "created_at": "2021-03-18T03:52:32Z",
            "html_url": "https://github.com/GenericMappingTools/pygmt/issues/717#issuecomment-801600394",
            "id": 801600394,
            "issue_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgwMTYwMDM5NA==",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/801600394/reactions"
            },
            "updated_at": "2021-03-18T03:52:32Z",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/comments/801600394",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
                "events_url": "https://api.github.com/users/seisman/events{/privacy}",
                "followers_url": "https://api.github.com/users/seisman/followers",
                "following_url": "https://api.github.com/users/seisman/following{/other_user}",
                "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/seisman",
                "id": 3974108,
                "login": "seisman",
                "node_id": "MDQ6VXNlcjM5NzQxMDg=",
                "organizations_url": "https://api.github.com/users/seisman/orgs",
                "received_events_url": "https://api.github.com/users/seisman/received_events",
                "repos_url": "https://api.github.com/users/seisman/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/seisman"
            }
        }
    ],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717/comments",
    "created_at": "2020-12-07T08:52:40Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/717",
    "id": 758307274,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        },
        {
            "color": "0e8a16",
            "default": true,
            "description": "Helping hands are appreciated",
            "id": 729911674,
            "name": "help wanted",
            "node_id": "MDU6TGFiZWw3Mjk5MTE2NzQ=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/help%20wanted"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3NTgzMDcyNzQ=",
    "number": 717,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 1,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717/timeline",
    "title": "Error while using the DEM.grd as a numpy variable",
    "updated_at": "2021-03-18T04:43:56Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/717",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/22539993?v=4",
        "events_url": "https://api.github.com/users/vivigb/events{/privacy}",
        "followers_url": "https://api.github.com/users/vivigb/followers",
        "following_url": "https://api.github.com/users/vivigb/following{/other_user}",
        "gists_url": "https://api.github.com/users/vivigb/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/vivigb",
        "id": 22539993,
        "login": "vivigb",
        "node_id": "MDQ6VXNlcjIyNTM5OTkz",
        "organizations_url": "https://api.github.com/users/vivigb/orgs",
        "received_events_url": "https://api.github.com/users/vivigb/received_events",
        "repos_url": "https://api.github.com/users/vivigb/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/vivigb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vivigb/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/vivigb"
    }
}