{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "**Description of the problem**\r\n\r\n`Figure.savefig()` reports errors when saving an image to a subdirectory that doesn't exist. The error messages are very confusing. \r\n\r\nI think we should check if the parent directory of the image exists before saving an image. If the directory doesn't exist, we have two options:\r\n\r\n1. Report that parent directories are missing and users should create these directories manually\r\n2. Create any missing parent directories automatically before saving \r\n\r\n**Full code that generated the error**\r\n\r\n```python\r\nimport pygmt\r\nfig = pygmt.Figure()\r\nfig.basemap(region=[101, 108.5, 26, 29], projection=\"M15c\", frame=True)\r\nfig.savefig(\"anypath/map.png\")\r\n```\r\n\r\n**Full error message**\r\n\r\n```\r\nGPL Ghostscript 9.55.0: **** Could not open the file 'anypath/map.png'.\r\nError: /invalidfileaccess in --showpage--\r\nOperand stack:\r\n   1   true\r\nExecution stack:\r\n   %interp_exit   .runexec2   --nostringval--   showpage   --nostringval--   2   %stopped_push   --nostringval--   showpage   showpage   false   1   %stopped_push   1974   1   3   %oparray_pop   1973   1   3   %oparray_pop   1961   1   3   %oparray_pop   1817   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   showpage   --nostringval--   2   %stopped_push   --nostringval--   1824   0   4   %oparray_pop   showpage   showpage\r\nDictionary stack:\r\n   --dict:776/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--   --dict:158/250(L)--\r\nCurrent allocation mode is local\r\nLast OS error: No such file or directory\r\nCurrent file position is 24898\r\nGPL Ghostscript 9.55.0: Unrecoverable error, exit code 1\r\npsconvert [ERROR]: System call [gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=2 -sDEVICE=png16m  -g1904x872 -r300 -sOutputFile='anypath/map.png' '/home/seisman/.gmt/sessions/gmt_session.90482/psconvert_90482d.eps'] returned error 256.\r\n---------------------------------------------------------------------------\r\nGMTCLibError                              Traceback (most recent call last)\r\nInput In [6], in <cell line: 1>()\r\n----> 1 fig.savefig(\"anypath/map.png\")\r\n\r\nFile ~/OSS/gmt/pygmt/pygmt/figure.py:318, in Figure.savefig(self, fname, transparent, crop, anti_alias, show, **kwargs)\r\n    315 if ext == \"kml\":\r\n    316     kwargs[\"W\"] = \"+k\"\r\n--> 318 self.psconvert(prefix=prefix, fmt=fmt, crop=crop, **kwargs)\r\n    319 if show:\r\n    320     launch_external_viewer(fname)\r\n\r\nFile ~/OSS/gmt/pygmt/pygmt/helpers/decorators.py:585, in use_alias.<locals>.alias_decorator.<locals>.new_module(*args, **kwargs)\r\n    580         msg = (\r\n    581             f\"Short-form parameter ({short_param}) is not recommended. \"\r\n    582             f\"Use long-form parameter '{long_alias}' instead.\"\r\n    583         )\r\n    584         warnings.warn(msg, category=SyntaxWarning, stacklevel=2)\r\n--> 585 return module_func(*args, **kwargs)\r\n\r\nFile ~/OSS/gmt/pygmt/pygmt/helpers/decorators.py:725, in kwargs_to_strings.<locals>.converter.<locals>.new_module(*args, **kwargs)\r\n    723             kwargs[arg] = separators[fmt].join(f\"{item}\" for item in value)\r\n    724 # Execute the original function and return its output\r\n--> 725 return module_func(*args, **kwargs)\r\n\r\nFile ~/OSS/gmt/pygmt/pygmt/figure.py:251, in Figure.psconvert(self, icc_gray, **kwargs)\r\n    248     raise GMTInvalidInput(\"The 'prefix' must be specified.\") from err\r\n    250 with Session() as lib:\r\n--> 251     lib.call_module(\r\n    252         module=\"psconvert\", args=f\"{prefix_arg} {build_arg_string(kwargs)}\"\r\n    253     )\r\n\r\nFile ~/OSS/gmt/pygmt/pygmt/clib/session.py:506, in Session.call_module(self, module, args)\r\n    502 status = c_call_module(\r\n    503     self.session_pointer, module.encode(), mode, args.encode()\r\n    504 )\r\n    505 if status != 0:\r\n--> 506     raise GMTCLibError(\r\n    507         f\"Module '{module}' failed with status code {status}:\\n{self._error_message}\"\r\n    508     )\r\n\r\nGMTCLibError: Module 'psconvert' failed with status code 79:\r\npsconvert [ERROR]: System call [gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=2 -sDEVICE=png16m  -g1904x872 -r300 -sOutputFile='anypath/map.png' '/home/seisman/.gmt/sessions/gmt_session.90482/psconvert_90482d.eps'] returned error 256.\r\n```\r\n\r\n**System information**\r\n\r\nPlease paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`:\r\n\r\n```\r\nPyGMT information:\r\n  version: v0.7.1.dev47+gcfc20a70\r\nSystem information:\r\n  python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]\r\n  executable: /home/seisman/opt/miniconda/bin/python\r\n  machine: Linux-5.18.11-200.fc36.x86_64-x86_64-with-glibc2.35\r\nDependency information:\r\n  numpy: 1.22.4\r\n  pandas: 1.4.2\r\n  xarray: 2022.3.0\r\n  netCDF4: 1.5.8\r\n  packaging: 21.3\r\n  geopandas: None\r\n  ghostscript: 9.55.0\r\n  gmt: 6.5.0_111fa6d_2022.08.11\r\nGMT library information:\r\n  binary dir: /home/seisman/opt/miniconda/bin\r\n  cores: 80\r\n  grid layout: rows\r\n  library path: /home/seisman/opt/GMT-master/lib64/libgmt.so\r\n  padding: 2\r\n  plugin dir: /home/seisman/opt/GMT-master/lib64/gmt/plugins\r\n  share dir: /home/seisman/opt/GMT-master/share\r\n  version: 6.5.0\r\n```",
    "closed_at": "2022-10-29T14:07:01Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    },
    "comments": 0,
    "comments_content": [],
    "comments_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/2092/comments",
    "created_at": "2022-08-30T02:17:28Z",
    "events_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/2092/events",
    "html_url": "https://github.com/GenericMappingTools/pygmt/issues/2092",
    "id": 1355073858,
    "labels": [
        {
            "color": "ee0701",
            "default": true,
            "description": "Something isn't working",
            "id": 563309827,
            "name": "bug",
            "node_id": "MDU6TGFiZWw1NjMzMDk4Mjc=",
            "url": "https://api.github.com/repos/GenericMappingTools/pygmt/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/2092/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 164,
        "created_at": "2022-06-12T13:10:39Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
            "events_url": "https://api.github.com/users/seisman/events{/privacy}",
            "followers_url": "https://api.github.com/users/seisman/followers",
            "following_url": "https://api.github.com/users/seisman/following{/other_user}",
            "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/seisman",
            "id": 3974108,
            "login": "seisman",
            "node_id": "MDQ6VXNlcjM5NzQxMDg=",
            "organizations_url": "https://api.github.com/users/seisman/orgs",
            "received_events_url": "https://api.github.com/users/seisman/received_events",
            "repos_url": "https://api.github.com/users/seisman/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/seisman"
        },
        "description": "",
        "due_on": "2022-11-01T07:00:00Z",
        "html_url": "https://github.com/GenericMappingTools/pygmt/milestone/14",
        "id": 8073518,
        "labels_url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/14/labels",
        "node_id": "MI_kwDOBRZfO84AezEu",
        "number": 14,
        "open_issues": 62,
        "state": "open",
        "title": "0.8.0",
        "updated_at": "2022-11-07T11:23:55Z",
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/milestones/14"
    },
    "node_id": "I_kwDOBRZfO85QxMlC",
    "number": 2092,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/2092/reactions"
    },
    "repository_url": "https://api.github.com/repos/GenericMappingTools/pygmt",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/2092/timeline",
    "title": "Figure.savefig() reports confusing errors when saving image into a non-existent directory",
    "updated_at": "2022-10-29T14:07:02Z",
    "url": "https://api.github.com/repos/GenericMappingTools/pygmt/issues/2092",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3974108?v=4",
        "events_url": "https://api.github.com/users/seisman/events{/privacy}",
        "followers_url": "https://api.github.com/users/seisman/followers",
        "following_url": "https://api.github.com/users/seisman/following{/other_user}",
        "gists_url": "https://api.github.com/users/seisman/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seisman",
        "id": 3974108,
        "login": "seisman",
        "node_id": "MDQ6VXNlcjM5NzQxMDg=",
        "organizations_url": "https://api.github.com/users/seisman/orgs",
        "received_events_url": "https://api.github.com/users/seisman/received_events",
        "repos_url": "https://api.github.com/users/seisman/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seisman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seisman/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seisman"
    }
}